### ISSUE TITLE
Unable to access PSI Probe on Tomee 1.7.4

### ISSUE THREAD

**Issue by moffit** [psi-probe/psi-probe#1073]
I have built and deployed PSI Probe to Tomee without issue.  The tomcat manager shows the application as deployed and running.  When I hit PSI Probe for the first time, after authentication, I get an HTTP 500 error.  The only error I can find is in the localhost.2017-05-29.log file.

The error appears to be a missing compiled JSP file, but that might not be the root cause:

Caused by: java.lang.ClassNotFoundException: org.apache.jsp.WEB_002dINF.jsp.errors.servleterror_jsp
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:132)
        at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:63)
        at org.apache.tomee.catalina.JavaeeInstanceManager.newInstance(JavaeeInstanceManager.java:66)
        at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:172)
        ... 46 more

I also noticed in the probe.log, on an regular basis:

23:25:10.001 ERROR {Probe_Quartz-3} [psiprobe.model.stats.StatsCollection] Could not delete file stats.xml.1
23:25:10.001 ERROR {Probe_Quartz-3} [psiprobe.model.stats.StatsCollection] Could not rename file stats.xml to stats.xml.1
23:25:10.001 ERROR {Probe_Quartz-3} [psiprobe.model.stats.StatsCollection] Could not write stats data to '/usr/apache-tomee-plus-1.7.4/work/Catalina/localhost/probe/stats.xml'
java.io.FileNotFoundException: /usr/apache-tomee-plus-1.7.4/work/Catalina/localhost/probe/stats.xml (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at psiprobe.model.stats.StatsCollection.serialize(StatsCollection.java:247)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Comment by hazendaz** [comment]
JSP pages are not delivered compiled as it would vary per install.  The delete/rename issues on stats.xml are fairly common in that those have existed as long as I've been working on the project only they use to never check the status and I made it check the status thus the output.

So it would appear the JSP issue is the true issue.  Does tomee not compile jsp pages by default?  I haven't actually used tomee in testing myself.  I generally just use straight tomcat and then only 7.0.x, 8.0.x, 8.5.x, and 9.0.x.  There are other variations such as jboss that will work with this but I simply don't have the time to test everything.  What I would suggest to perform a simple test is to use the equivelant tomcat 7 that tomee 1.7.4 matches which I believe is 7.0.68.  Once confirmed working there, then hunt down the issue with JSP not compiling.

I can try to bring this up on tomee but not sure when I might get time to do so.

**Comment by moffit** [comment]
Hi hazendaz - you are correct, thank you for pointing that out.  I only had JSF apps running on the server, which don't compile down to JSPs.  The /work/Catalina folder was actually owned by root and not tomee, which prevented the JSPs, among other things, from being compiled.  All is working well now.

**Comment by hazendaz** [comment]
Glad you got it going!
