### ISSUE TITLE
Error while running 3.0.0-RC2 OS/Hardware Info

### ISSUE THREAD

**Issue by mattbishop** [psi-probe/psi-probe#1107]
First time I am running 3.0.0-RC2. I clicked on the OS/Hardware Info and received this exception:

```21-Sep-2017 22:15:12.155 SEVERE [http-apr-80-exec-22] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [probe] in context with path [/probe] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Illegal Capacity: -943823872] with root cause
 java.lang.IllegalArgumentException: Illegal Capacity: -943823872
        at java.util.ArrayList.<init>(ArrayList.java:142)
        at oshi.software.os.mac.MacOperatingSystem.getCommandLine(MacOperatingSystem.java:226)
        at oshi.software.os.mac.MacOperatingSystem.getProcess(MacOperatingSystem.java:191)
        at oshi.software.os.mac.MacOperatingSystem.getProcesses(MacOperatingSystem.java:94)
        at psiprobe.controllers.oshi.OshiController.printProcesses(OshiController.java:267)
        at psiprobe.controllers.oshi.OshiController.handleRequestInternal(OshiController.java:112)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)
        at psiprobe.controllers.oshi.OshiController.handleRequest(OshiController.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:121)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:595)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at psiprobe.Tomcat85AgentValve.invoke(Tomcat85AgentValve.java:40)
        at psiprobe.Tomcat85AgentValve.invoke(Tomcat85AgentValve.java:40)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2298)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mattbishop** [comment]
Here is my startup log:

```21-Sep-2017 21:58:07.415 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.20
21-Sep-2017 21:58:07.420 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 2 2017 21:35:49 UTC
21-Sep-2017 21:58:07.420 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.20.0
21-Sep-2017 21:58:07.421 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Mac OS X
21-Sep-2017 21:58:07.421 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.7.5
21-Sep-2017 21:58:07.421 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          x86_64
21-Sep-2017 21:58:07.421 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre
21-Sep-2017 21:58:07.422 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.7.0_80-b15
21-Sep-2017 21:58:07.422 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
21-Sep-2017 21:58:07.422 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /Library/Tomcat/8.5.20
21-Sep-2017 21:58:07.422 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /Library/Tomcat/8.5.20
21-Sep-2017 21:58:07.423 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/Library/Tomcat/Home/conf/logging.properties
21-Sep-2017 21:58:07.423 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
21-Sep-2017 21:58:07.423 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote
21-Sep-2017 21:58:07.423 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
21-Sep-2017 21:58:07.423 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
21-Sep-2017 21:58:07.424 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
21-Sep-2017 21:58:07.424 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.library.path=/opt/local/lib
21-Sep-2017 21:58:07.424 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/Library/Tomcat/Home
21-Sep-2017 21:58:07.424 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/Library/Tomcat/Home
21-Sep-2017 21:58:07.424 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/Library/Tomcat/Home/temp
21-Sep-2017 21:58:07.424 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.14] using APR version [1.6.2].
21-Sep-2017 21:58:07.424 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
21-Sep-2017 21:58:07.425 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [true], useOpenSSL [true]
21-Sep-2017 21:58:07.430 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.0.2l  25 May 2017]
21-Sep-2017 21:58:07.667 INFO [main] org.apache.coyote.http11.AbstractHttp11Protocol.configureUpgradeProtocol The ["http-apr-80"] connector has been configured to support HTTP upgrade to [h2c]
21-Sep-2017 21:58:07.668 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-apr-80"]
21-Sep-2017 21:58:07.693 INFO [main] org.apache.coyote.http11.AbstractHttp11Protocol.configureUpgradeProtocol The ["https-openssl-apr-443"] connector has been configured to support negotiation to [h2] via ALPN
21-Sep-2017 21:58:07.693 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["https-openssl-apr-443"]
21-Sep-2017 21:58:07.815 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1379 ms
21-Sep-2017 21:58:07.875 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
21-Sep-2017 21:58:07.876 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.20

**Comment by hazendaz** [comment]
This might be a mac related issue.  Because it is failing inside oshi, it might be worth checking that project to see what is causing it.  I can check next week on latest build to confirm if linux is ok with the latest version in use.  I don't have a mac so cannot check that.  Projece for oshi is at [github.com/oshi](https://github.com/oshi/oshi)

**Comment by hazendaz** [comment]
This is very experimental piece added to psi proble.  It's a cached dump of info because oshi was very slow to respond.  So after first time it is requested it won't update again.

**Comment by dbwiddis** [comment]
Can you post the method you are executing that causes this?

**Comment by mattbishop** [comment]
From the stack trace it looks like here: https://github.com/psi-probe/psi-probe/blob/master/core/src/main/java/psiprobe/controllers/oshi/OshiController.java#L267

**Comment by dbwiddis** [comment]
It's pre-coffee and I realized that just after I posted.  Further discussion will be on https://github.com/oshi/oshi/issues/412

**Comment by hazendaz** [comment]
Closing issue as this appeared fixed.
