### ISSUE TITLE
Hikari data source not visible

### ISSUE THREAD

**Issue by tim-oe** [psi-probe/psi-probe#1112]
tomcat 7.0.82
HikariCP 2.6.3
mariaDB 10.21
Psi-Probe 3.0.0.RC2

the data source tab shows nothing.

context.xml configuration for data source

    <Resource
            closeMethod="close"
            auth="Container"
            type="javax.sql.DataSource"
            name="jdbc/oeDatabase"
            factory="com.zaxxer.hikari.HikariJNDIFactory"
            driverClassName="org.mariadb.jdbc.Driver"
            idleTimeout="300000"
            maxLifetime="3600000"
            maximumPoolSize="30"
            minimumIdle="10"
            poolName="oeDatabase"
            registerMbeans="false"
            leakDetectionThreshold="30000"
            jdbcUrl="jdbc:mariadb://localhost:3306/xxx?user=xxxt&amp;password=xxx&amp;useServerPrepStmts=true&amp;prepStmtCacheSize=250&amp;prepStmtCacheSqlLimit=2048&amp;autoReconnect=true"			
          />

found the following exception in the logs:

16:38:00.062 INFO  {Probe_Quartz-3} [psiprobe.beans.ResourceResolverBean] reading resource jndi name: java:comp/env/jdbc/oeDatabase
16:38:00.063 ERROR {Probe_Quartz-3} [psiprobe.beans.ResourceResolverBean] Failed to lookup: 'jdbc/oeDatabase'
java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy99.getActiveConnections(Unknown Source)
	at psiprobe.beans.accessors.HikariCpDatasourceAccessor.getInfo(HikariCpDatasourceAccessor.java:42)
	at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:163)
	at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:124)
	at psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:222)
	at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:206)
	at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: javax.management.InstanceNotFoundException: com.zaxxer.hikari:type=Pool (oeDatabase)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at com.sun.jmx.mbeanserver.MXBeanProxy$GetHandler.invoke(MXBeanProxy.java:122)
	at com.sun.jmx.mbeanserver.MXBeanProxy.invoke(MXBeanProxy.java:167)
	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:258)
	... 16 common frames omitted

**Comment by hazendaz** [comment]
@tim-oe Any help fixing would be appreciated.  I added a bunch of those in hopes someone would find them useful but not having used any of them myself they were mostly nice to haves.  If you can take a look at the code that is throwing the error and see if you can correct it that would be great!  Otherwise this might be sitting for a while as I'm pretty busy with other projects at the moment.

**Comment by hazendaz** [comment]
closing as old and haven't heard more so its probably working now.  If not please reopen.

**Comment by ChrissW-R1** [comment]
I have the same issue. Which information should I provide?

Apache Tomcat 9.0.80
HikariCP 5.0.1
PostgreSQL 15.4.0
Psi Probe 3.7.3

Log:
`21:52:00.002 ERROR {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Failed to lookup: 'globaldb'
java.lang.reflect.UndeclaredThrowableException: null
	at jdk.proxy2/jdk.proxy2.$Proxy50.getActiveConnections(Unknown Source)
	at psiprobe.beans.accessors.HikariCpDatasourceAccessor.getInfo(HikariCpDatasourceAccessor.java:42)
	at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:163)
	at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:84)
	at psiprobe.beans.ContainerWrapperBean.getGlobalDataSources(ContainerWrapperBean.java:241)
	at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:207)
	at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:283)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: javax.management.InstanceNotFoundException: com.zaxxer.hikari:type=Pool (HikariPool-1)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1088)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:640)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:679)
	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy$GetHandler.invoke(MXBeanProxy.java:122)
	at java.management/com.sun.jmx.mbeanserver.MXBeanProxy.invoke(MXBeanProxy.java:167)
	at java.management/javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:258)
	... 16 common frames omitted`

**Comment by hazendaz** [comment]
Does this help https://stackoverflow.com/questions/24322737/hikaricp-1-4-0-mbean-instancenotfoundexception

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ChrissW-R1** [comment]
There is no source code I could change directly. I added the datasource in the server.xml and added Psi Probe as webapp. After this I get this issue above.

**Comment by hazendaz** [comment]
@ChrissW-R1 Can you build from and test the latest master here?  I've made a fix that should resolve the issue noted here by using directly available hikari jmx bean.  Before it was trying to proxy to it.
