### ISSUE TITLE
NoSuchMethod Error in /probe/servlets

### ISSUE THREAD

**Issue by Cypher1** [psi-probe/psi-probe#1117]
Psi-probe told me to post here, sorry about my formatting.

```
org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.NoSuchMethodError: org.apache.catalina.core.StandardWrapper.isSingleThreadModel()Z
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:924)
	at com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:54)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:603)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:542)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:905)
	at org.apache.jsp.WEB_002dINF.jsp.servlets_jsp._jspService(servlets_jsp.java:182)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:410)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:236)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:257)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1183)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:902)
	at com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:54)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:615)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.apache.catalina.core.StandardWrapper.isSingleThreadModel()Z
	at com.googlecode.psiprobe.tools.ApplicationUtils.getServletInfo(ApplicationUtils.java:354)
	at com.googlecode.psiprobe.tools.ApplicationUtils.getApplicationServlets(ApplicationUtils.java:365)
	at com.googlecode.psiprobe.controllers.servlets.ListServletsController.handleContext(ListServletsController.java:46)
	at com.googlecode.psiprobe.controllers.ContextHandlerController.handleRequestInternal(ContextHandlerController.java:35)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
	... 66 more
```

**Comment by hazendaz** [comment]
What version of psi probe and which tomcat are you using?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Cypher1** [comment]
I'm doing a WebApps course at my university.
We've been required to use Apache Tomcat 7.0.82 and Psi-Probe 3.0.0-SNAPSHOT (from pom.xml).

**Comment by hazendaz** [comment]
So that class is in tomcat 7.0.82, see [here](https://github.com/apache/tomcat70/search?utf8=%E2%9C%93&q=isSingleThreadModel&type=).  I'll have to look at the code as that is long deprecated in tomcat and likely removed in newer versions but not quite sure why that is happening.  Can you provide me steps to recreate the issue such as was this at startup or during some navigation in psi probe?

**Comment by Cypher1** [comment]
Steps to repro:
1. Startup Tomcat and then psi-probe
2. Load in the .war file for my assignment
3. Open psi-probe
4. Open the servlets page for the assignment 'webapp'.

It might be to do with my code but the code runs properly and has servlets, so I'm not sure how it would be broken there. I'm not doing anything interesting with my classes that extend Servelet (e.g. overwriting methods).

Thanks

**Comment by hazendaz** [comment]
@Cypher1 I'm pretty sure you are not using the latest build from master.  The error indicated in your stack trace is actually no longer a present line and it was over a year ago.  Can you please run a build from master and let me know if this issue is still present?

**Comment by Cypher1** [comment]
Thanks, if the line is gone then I'm pretty happy to close this and trust
that it has been fixed in future versions.
I am no longer running the site that was causing the bug and am on holiday
until I start work at my new job.

Thanks for the help, sorry for the old bug.

**Comment by hazendaz** [comment]
Thanks.  I'll go ahead and close this out.  If you happen upon it again, please let me know.

**Comment by Cypher1** [comment]
Will do. Thanks!
