### ISSUE TITLE
Upgraded to Tomcat 8.  Now getting "Application encountered an unexpected error" when first running Probe

### ISSUE THREAD

**Issue by bridgeroom** [psi-probe/psi-probe#1127]
We had been using PSI-Probe 2.3.3 for several years on our tomcat 7 servers.  Our vendor forced us to upgrade to Tomcat 8.5.9, in the summer of 2017.

Now that we upgraded to PSI-Probe 3.0.0 RC2, we are now getting this error message:

>

> There was an error
> 
> 
> Application encountered an unexpected error. Please check the Tomcat logs. We will greatly appreciate it if you share the information with us. Sharing this information through our issue tracker or our discussion board will help us find and correct this problem as soon as possible! 

> 

I assume that we need to go to PSI-Probe 3.0.0, as it seems to be compatible with Tomcat 8, where as 2.3.3 is not, right?

I spoke to another user at another school board who had the same issue.  He said that if he just installed Tomcat 8 and then only PSI-Probe, Probe worked.  But once he installed our vendor's webapps, it gave him that same message (as above).

We noticed this after we upgraded Tomcat in the summer of 2017.  Although its not mission critical at that time, we have put this off long enough and now need a solution.

Here is an extract from the "Probe.log" file today from the beginning:

`00:00:00.007 INFO  {Probe_Quartz-3} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT 
00:00:00.007 INFO  {Probe_Quartz-3} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebservices-auth
00:00:00.007 INFO  {Probe_Quartz-3} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
00:00:00.007 INFO  {Probe_Quartz-3} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebschool
00:00:00.007 INFO  {Probe_Quartz-3} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
00:00:00.007 INFO  {Probe_Quartz-3} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /docs
00:00:00.007 INFO  {Probe_Quartz-3} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebschadmin
00:00:00.007 INFO  {Probe_Quartz-3} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
00:00:00.007 INFO  {Probe_Quartz-3} [psiprobe.Tomcat85ContainerAdapter] reading resource: cas
00:00:00.007 INFO  {Probe_Quartz-3} [psiprobe.Tomcat85ContainerAdapter] reading resource: etrilliumMail/Session
00:00:00.007 ERROR {Probe_Quartz-3} [org.quartz.core.JobRunShell] Job DEFAULT.datasourceStatsJobDetail threw an unhandled Exception: 
org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean] failed; nested exception is java.lang.NoClassDefFoundError: javax/mail/Authenticator
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NoClassDefFoundError: javax/mail/Authenticator
	at org.apache.naming.factory.MailSessionFactory.getObjectInstance(MailSessionFactory.java:104)
	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:94)
	at javax.naming.spi.NamingManager.getObjectInstance(Unknown Source)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:839)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:163)
	at javax.naming.InitialContext.lookup(Unknown Source)
	at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:142)
	at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:116)
	at psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:212)
	at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:196)
	at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
	at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	... 3 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.mail.Authenticator
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 26 common frames omitted
00:00:00.007 ERROR {Probe_Quartz-3} [org.quartz.core.ErrorLogger] Job (DEFAULT.datasourceStatsJobDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean] failed; nested exception is java.lang.NoClassDefFoundError: javax/mail/Authenticator
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/mail/Authenticator
	at org.apache.naming.factory.MailSessionFactory.getObjectInstance(MailSessionFactory.java:104)
	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:94)
	at javax.naming.spi.NamingManager.getObjectInstance(Unknown Source)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:839)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:163)
	at javax.naming.InitialContext.lookup(Unknown Source)
	at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:142)
	at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:116)
	at psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:212)
	at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:196)
	at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
	at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	... 3 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.mail.Authenticator
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 26 common frames omitted
00:02:00.006 INFO  {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT 
00:02:00.006 INFO  {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebservices-auth
00:02:00.006 INFO  {Probe_Quartz-2} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
00:02:00.006 INFO  {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebschool
00:02:00.006 INFO  {Probe_Quartz-2} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
00:02:00.006 INFO  {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /docs
00:02:00.006 INFO  {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebschadmin
00:02:00.006 INFO  {Probe_Quartz-2} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
00:02:00.006 INFO  {Probe_Quartz-2} [psiprobe.Tomcat85ContainerAdapter] reading resource: cas
00:02:00.006 INFO  {Probe_Quartz-2} [psiprobe.Tomcat85ContainerAdapter] reading resource: etrilliumMail/Session
00:02:00.006 ERROR {Probe_Quartz-2} [org.quartz.core.JobRunShell] Job DEFAULT.datasourceStatsJobDetail threw an unhandled Exception: 
org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean] failed; nested exception is java.lang.NoClassDefFoundError: javax/mail/Authenticator
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NoClassDefFoundError: javax/mail/Authenticator
	at org.apache.naming.factory.MailSessionFactory.getObjectInstance(MailSessionFactory.java:104)
	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:94)
	at javax.naming.spi.NamingManager.getObjectInstance(Unknown Source)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:839)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:163)
	at javax.naming.InitialContext.lookup(Unknown Source)
	at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:142)
	at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:116)
	at psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:212)
	at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:196)
	at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
	at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	... 3 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.mail.Authenticator
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 26 common frames omitted
00:02:00.006 ERROR {Probe_Quartz-2} [org.quartz.core.ErrorLogger] Job (DEFAULT.datasourceStatsJobDetail threw an exception.`

(This is a partial extract)

In addition, here are some lines from the same log file from a time around when I get the error, to the end:

`10:56:52.634 INFO  {http-nio-8080-exec-21} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT 
10:56:52.634 INFO  {http-nio-8080-exec-21} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebservices-auth
10:56:52.634 INFO  {http-nio-8080-exec-21} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
10:56:52.634 ERROR {http-nio-8080-exec-21} [psiprobe.tools.ApplicationUtils] Cannot determine Locale of 10.170.3.35:49359
10:56:52.634 INFO  {http-nio-8080-exec-21} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebschool
10:56:52.634 INFO  {http-nio-8080-exec-21} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
10:56:52.634 INFO  {http-nio-8080-exec-21} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /docs
10:56:52.634 ERROR {http-nio-8080-exec-21} [psiprobe.tools.ApplicationUtils] Cannot determine Locale of 10.170.3.83:49419
10:56:52.634 ERROR {http-nio-8080-exec-21} [psiprobe.tools.ApplicationUtils] Cannot determine Locale of 10.170.3.83:49459
10:56:52.634 ERROR {http-nio-8080-exec-21} [psiprobe.tools.ApplicationUtils] Cannot determine Locale of 10.170.3.83:49410
10:56:52.634 ERROR {http-nio-8080-exec-21} [psiprobe.tools.ApplicationUtils] Cannot determine Locale of 10.170.3.35:49345
10:56:52.634 INFO  {http-nio-8080-exec-21} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebschadmin
10:56:52.634 INFO  {http-nio-8080-exec-21} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
10:56:52.634 INFO  {http-nio-8080-exec-21} [psiprobe.Tomcat85ContainerAdapter] reading resource: cas
10:56:52.634 INFO  {http-nio-8080-exec-21} [psiprobe.Tomcat85ContainerAdapter] reading resource: etrilliumMail/Session
10:58:00.008 INFO  {Probe_Quartz-5} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT 
10:58:00.008 INFO  {Probe_Quartz-5} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebservices-auth
10:58:00.008 INFO  {Probe_Quartz-5} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
10:58:00.008 INFO  {Probe_Quartz-5} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebschool
10:58:00.008 INFO  {Probe_Quartz-5} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
10:58:00.008 INFO  {Probe_Quartz-5} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /docs
10:58:00.008 INFO  {Probe_Quartz-5} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebschadmin
10:58:00.008 INFO  {Probe_Quartz-5} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
10:58:00.008 INFO  {Probe_Quartz-5} [psiprobe.Tomcat85ContainerAdapter] reading resource: cas
10:58:00.008 INFO  {Probe_Quartz-5} [psiprobe.Tomcat85ContainerAdapter] reading resource: etrilliumMail/Session
10:58:00.008 ERROR {Probe_Quartz-5} [org.quartz.core.JobRunShell] Job DEFAULT.datasourceStatsJobDetail threw an unhandled Exception: 
org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean] failed; nested exception is java.lang.NoClassDefFoundError: javax/mail/Authenticator
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NoClassDefFoundError: javax/mail/Authenticator
	at org.apache.naming.factory.MailSessionFactory.getObjectInstance(MailSessionFactory.java:104)
	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:94)
	at javax.naming.spi.NamingManager.getObjectInstance(Unknown Source)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:839)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:163)
	at javax.naming.InitialContext.lookup(Unknown Source)
	at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:142)
	at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:116)
	at psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:212)
	at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:196)
	at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
	at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	... 3 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.mail.Authenticator
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 26 common frames omitted
10:58:00.008 ERROR {Probe_Quartz-5} [org.quartz.core.ErrorLogger] Job (DEFAULT.datasourceStatsJobDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean] failed; nested exception is java.lang.NoClassDefFoundError: javax/mail/Authenticator
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/mail/Authenticator
	at org.apache.naming.factory.MailSessionFactory.getObjectInstance(MailSessionFactory.java:104)
	at org.apache.naming.factory.FactoryBase.getObjectInstance(FactoryBase.java:94)
	at javax.naming.spi.NamingManager.getObjectInstance(Unknown Source)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:839)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:159)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:827)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:173)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:163)
	at javax.naming.InitialContext.lookup(Unknown Source)
	at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:142)
	at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:116)
	at psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:212)
	at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:196)
	at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
	at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	... 3 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.mail.Authenticator
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 26 common frames omitted
10:58:12.571 INFO  {http-nio-8080-exec-15} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT 
10:58:12.571 INFO  {http-nio-8080-exec-15} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebservices-auth
10:58:12.571 INFO  {http-nio-8080-exec-15} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
10:58:12.571 ERROR {http-nio-8080-exec-15} [psiprobe.tools.ApplicationUtils] Cannot determine Locale of 10.170.3.35:49359
10:58:12.571 INFO  {http-nio-8080-exec-15} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebschool
10:58:12.571 INFO  {http-nio-8080-exec-15} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium
10:58:12.571 INFO  {http-nio-8080-exec-15} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /docs
10:58:12.571 ERROR {http-nio-8080-exec-15} [psiprobe.tools.ApplicationUtils] Cannot determine Locale of 10.170.3.83:49419
10:58:12.571 ERROR {http-nio-8080-exec-15} [psiprobe.tools.ApplicationUtils] Cannot determine Locale of 10.170.3.83:49459
10:58:12.571 ERROR {http-nio-8080-exec-15} [psiprobe.tools.ApplicationUtils] Cannot determine Locale of 10.170.3.83:49410
10:58:12.571 ERROR {http-nio-8080-exec-15} [psiprobe.tools.ApplicationUtils] Cannot determine Locale of 10.170.3.35:49345
10:58:12.571 INFO  {http-nio-8080-exec-15} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /twebschadmin
10:58:12.571 INFO  {http-nio-8080-exec-15} [psiprobe.Tomcat85ContainerAdapter] reading resource: jdbc/trillium`

Let me know if you need any more info of explanation. 

We have several webapps that run our school board's student admin system.  For example, some names of these webapps are twebschadmin, twebschool, twebea, cas, etc.  

We use PSI-Probe to monitor what IP addresses are running what web apps.  We have multiple webservers running the same apps, running under a Barracuda load balancer.  These servers are on Windows 2012.

Could there be something in the vendor's webapps that is conflicting with Probe?  The webapps work fine in Tomcat 8.  Obviously these web apps have been updated to work with Tomcat 8.

The lines like "Cannot determine Locale of 10.170.3.35:49345" at the end seem to be a new wrinkle that I had not seen before, even when I had this issue earlier in September 2017.  

The information in the log files is quite confusing to me, so I would appreciate some assistance in determining what the problem is and any possible solutions.

**Comment by hazendaz** [comment]
I think there is a bit of classloader leak.  You are on the right version.  It works now on tomcat 8.0, 8.5, and 9.0.  The specific error looks like you might have a very old java mail in your application.  That library is very backwards compatible so using 1.5.5+ should solve the issue.  If you could, can you provide a listing of the jars either additionally added to tomcat or within your war?  You can exclude private jars from the list and for added security you can send to my personal email at jeremylandis@hotmail.com.  this will allow me to setup a dummy app with same structure so I can triage why that occurs and see what I can do to resolve it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bridgeroom** [comment]
Hi Jeremy,

I replied to your personal email address on Wednesday (see below).  It included 3 txt files as attachments.  Did you receive my email?  I appreciate your offer to look into this.

Thank you,
 
David Druiett

**Comment by hazendaz** [comment]
Hi,  got it!  Planning to look this weekend

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bridgeroom** [comment]
Thanks so much.

David

On Jan 12, 2018, at 5:43 PM, Jeremy Landis <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi, got it! Planning to look this weekend

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
@bridgeroom Where you able to test moving java mail into tomcat/lib to see if that got around this issue?

**Comment by hazendaz** [comment]
@bridgeroom Any update on this?  Did moving java mail as suggested fix your issue?

**Comment by hazendaz** [comment]
Closing issue due to non response.  Most likely if javax.mail is moved to tomcat/lib the issue will go away.
