### ISSUE TITLE
Graphics not Working

### ISSUE THREAD

**Issue by sepphuber** [psi-probe/psi-probe#1166]
Hi,

on my upgraded Debian Stretch systems with psi-probe 3.0.0 Release all the graphics/charts are not working. As you can see the "-Djava.awt.headless=true" is set in my jvm parameters.
The Exception is "org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.jfree.chart.JFreeChart"

My System Parameters:
_Tomcat/8.5.14 (Debian)
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-1~deb9u1-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
/usr/lib/jvm/default-java/bin/java -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.awt.headless=true -Duser.language=de -Duser.country=DE -Xmx6144m -XX:MaxPermSize=512M -XX:+UseConcMarkSweepGC -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -classpath /usr/share/tomcat8/bin/bootstrap.jar:/usr/share/tomcat8/bin/tomcat-juli.jar -Dcatalina.base=/var/lib/tomcat8 -Dcatalina.home=/usr/share/tomcat8 -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp org.apache.catalina.startup.Bootstrap start_

`
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.u.matcher.AntPathRequestMatcher] Request '/chart.png' matched by universal pattern '/**'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.security.web.FilterChainProxy] /chart.png?p=memory_usage&sp=Compressed+Class+Space&xz=228&yz=120&l=false&t=1524668980698 at position 1 of 5 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.c.HttpSessionSecurityContextRepository] Obtained a valid SecurityContext from SPRING_SECURITY_CONTEXT: 'org.springframework.security.core.context.SecurityContextImpl@cb5a580d: Authentication: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken@cb5a580d: Principal: org.springframework.security.core.userdetails.User@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_MANAGER; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.preauth.PreAuthenticatedGrantedAuthoritiesWebAuthenticationDetails@ffff6a82: RemoteIpAddress: 192.168.1.109; SessionId: null; [ROLE_MANAGER]; Granted Authorities: ROLE_MANAGER'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.security.web.FilterChainProxy] /chart.png?p=memory_usage&sp=Compressed+Class+Space&xz=228&yz=120&l=false&t=1524668980698 at position 2 of 5 in additional filter chain; firing Filter: 'J2eePreAuthenticatedProcessingFilter'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.a.p.j.J2eePreAuthenticatedProcessingFilter] Checking secure context token: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken@cb5a580d: Principal: org.springframework.security.core.userdetails.User@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_MANAGER; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.preauth.PreAuthenticatedGrantedAuthoritiesWebAuthenticationDetails@ffff6a82: RemoteIpAddress: 192.168.1.109; SessionId: null; [ROLE_MANAGER]; Granted Authorities: ROLE_MANAGER
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.security.web.FilterChainProxy] /chart.png?p=memory_usage&sp=Compressed+Class+Space&xz=228&yz=120&l=false&t=1524668980698 at position 3 of 5 in additional filter chain; firing Filter: 'LogoutFilter'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.u.matcher.AntPathRequestMatcher] Checking match of request : '/chart.png'; against '/logout'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.security.web.FilterChainProxy] /chart.png?p=memory_usage&sp=Compressed+Class+Space&xz=228&yz=120&l=false&t=1524668980698 at position 4 of 5 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.security.web.FilterChainProxy] /chart.png?p=memory_usage&sp=Compressed+Class+Space&xz=228&yz=120&l=false&t=1524668980698 at position 5 of 5 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.u.matcher.AntPathRequestMatcher] Checking match of request : '/chart.png'; against '/adm/**'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.u.matcher.AntPathRequestMatcher] Checking match of request : '/chart.png'; against '/adm/restartvm.ajax'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.u.matcher.AntPathRequestMatcher] Checking match of request : '/chart.png'; against '/sql/**'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.u.matcher.AntPathRequestMatcher] Checking match of request : '/chart.png'; against '/app/**'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.u.matcher.AntPathRequestMatcher] Request '/chart.png' matched by universal pattern '/**'
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.a.i.FilterSecurityInterceptor] Secure object: FilterInvocation: URL: /chart.png?p=memory_usage&sp=Compressed+Class+Space&xz=228&yz=120&l=false&t=1524668980698; Attributes: [ROLE_PROBEUSER, ROLE_POWERUSER, ROLE_POWERUSERPLUS, ROLE_MANAGER, ROLE_MANAGER-GUI]
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.a.i.FilterSecurityInterceptor] Previously Authenticated: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken@cb5a580d: Principal: org.springframework.security.core.userdetails.User@586034f: Username: admin; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_MANAGER; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.preauth.PreAuthenticatedGrantedAuthoritiesWebAuthenticationDetails@ffff6a82: RemoteIpAddress: 192.168.1.109; SessionId: null; [ROLE_MANAGER]; Granted Authorities: ROLE_MANAGER
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.access.vote.AffirmativeBased] Voter: org.springframework.security.access.vote.RoleVoter@3583bf51, returned: 1
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.a.i.FilterSecurityInterceptor] Authorization successful
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.s.w.a.i.FilterSecurityInterceptor] RunAsManager did not change Authentication object
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.security.web.FilterChainProxy] /chart.png?p=memory_usage&sp=Compressed+Class+Space&xz=228&yz=120&l=false&t=1524668980698 reached end of additional filter chain; proceeding with original chain
17:11:26.358 DEBUG {http-nio-8080-exec-6} [psiprobe.ProbeServlet] DispatcherServlet with name 'probe' processing GET request for [/probe/chart.png]
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.w.s.m.m.a.RequestMappingHandlerMapping] Looking up handler method for path /chart.png
17:11:26.358 DEBUG {http-nio-8080-exec-6} [o.s.w.s.m.m.a.RequestMappingHandlerMapping] Returning handler method [public org.springframework.web.servlet.ModelAndView psiprobe.controllers.RenderChartController.handleRequest(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception]
17:11:26.358 DEBUG {http-nio-8080-exec-6} [psiprobe.ProbeServlet] Last-Modified value for [/probe/chart.png] is: -1
17:11:26.359 DEBUG {http-nio-8080-exec-6} [o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver] Resolving exception from handler [public org.springframework.web.servlet.ModelAndView psiprobe.controllers.RenderChartController.handleRequest(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception]: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.jfree.chart.JFreeChart
17:11:26.359 DEBUG {http-nio-8080-exec-6} [o.s.w.s.m.a.ResponseStatusExceptionResolver] Resolving exception from handler [public org.springframework.web.servlet.ModelAndView psiprobe.controllers.RenderChartController.handleRequest(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception]: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.jfree.chart.JFreeChart
17:11:26.359 DEBUG {http-nio-8080-exec-6} [o.s.w.s.m.s.DefaultHandlerExceptionResolver] Resolving exception from handler [public org.springframework.web.servlet.ModelAndView psiprobe.controllers.RenderChartController.handleRequest(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception]: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.jfree.chart.JFreeChart
17:11:26.359 DEBUG {http-nio-8080-exec-6} [psiprobe.ProbeServlet] Could not complete request
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.jfree.chart.JFreeChart
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982)
at psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:82)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:121)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:595)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at psiprobe.Tomcat85AgentValve.invoke(Tomcat85AgentValve.java:35)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.ha.session.JvmRouteBinderValve.invoke(JvmRouteBinderValve.java:193)
at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:322)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jfree.chart.JFreeChart
at org.jfree.chart.ChartFactory.createXYAreaChart(ChartFactory.java:1870)
at psiprobe.controllers.RenderChartController.handleRequestInternal(RenderChartController.java:155)
at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)
at psiprobe.controllers.RenderChartController.handleRequest(RenderChartController.java:87)
at sun.reflect.GeneratedMethodAccessor309.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
... 53 common frames omitted
17:11:26.359 DEBUG {http-nio-8080-exec-6} [o.s.s.w.c.SecurityContextPersistenceFilter] SecurityContextHolder now cleared, as request processing completed
`

**Comment by sepphuber** [comment]
Thanks for the hint, unfortunately this was not the solution.
I use the Debian maintained package of the openjdk, the libs where already installed as dependencies.

When I use an old standard sun jdk it works!
_java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) Server VM (build 25.111-b14, mixed mode)_

After digging a bit deeper I found the solution - Debian specific (perhaps Ubuntu): 
The tomcat 8 package only installs the package "openjdk-8-jdk-headless".
After installing "openjdk-8-jdk" the graphics are displayed!

https://packages.debian.org/stretch/tomcat8

**Comment by oldphart4** [comment]
I had the same issue on Ubuntu 18.04 LTS and probe 3.1.0.  This behaviour does not occur on Ubuntu 16.04 LTS and probe 3.1.0.  Interestingly the java version is identical on both platforms (openjdk version "1.8.0_181").  It would be interesting to identify which library installed by non-headless openJDK resolves the issue as there were lots of (now superfluous) libraries and other bits and pieces installed as dependencies:
 apt install openjdk-8-jdk
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  adwaita-icon-theme at-spi2-core dconf-gsettings-backend dconf-service fontconfig fonts-dejavu-extra glib-networking
  glib-networking-common glib-networking-services gsettings-desktop-schemas gtk-update-icon-cache hicolor-icon-theme
  humanity-icon-theme libasound2 libasound2-data libasyncns0 libatk-bridge2.0-0 libatk-wrapper-java libatk-wrapper-java-jni
  libatk1.0-0 libatk1.0-data libatspi2.0-0 libcairo-gobject2 libcairo2 libcolord2 libcroco3 libdatrie1 libdconf1 libdrm-amdgpu1
  libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libegl-mesa0 libegl1 libepoxy0 libflac8 libfontenc1 libgbm1 libgdk-pixbuf2.0-0
  libgdk-pixbuf2.0-bin libgdk-pixbuf2.0-common libgif7 libgl1 libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libglvnd0
  libglx-mesa0 libglx0 libgraphite2-3 libgtk-3-0 libgtk-3-bin libgtk-3-common libharfbuzz0b libice-dev libice6 libjbig0
  libjson-glib-1.0-0 libjson-glib-1.0-common libllvm6.0 libogg0 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0
  libpciaccess0 libpixman-1-0 libproxy1v5 libpthread-stubs0-dev libpulse0 librest-0.7-0 librsvg2-2 librsvg2-common libsm-dev
  libsm6 libsndfile1 libsoup-gnome2.4-1 libsoup2.4-1 libthai-data libthai0 libtiff5 libvorbis0a libvorbisenc2 libwayland-client0
  libwayland-cursor0 libwayland-egl1-mesa libwayland-server0 libx11-dev libx11-doc libx11-xcb1 libxau-dev libxaw7 libxcb-dri2-0
  libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxcb1-dev
  libxcomposite1 libxcursor1 libxdamage1 libxdmcp-dev libxfixes3 libxft2 libxinerama1 libxkbcommon0 libxmu6 libxpm4 libxrandr2
  libxshmfence1 libxt-dev libxt6 libxv1 libxxf86dga1 libxxf86vm1 openjdk-8-jre ubuntu-mono x11-utils x11proto-core-dev
  x11proto-dev xorg-sgml-doctools xtrans-dev

We try to keep our production systems clear of superfluous packages.

**Comment by sepphuber** [comment]
Hi,

I have posted the solution here:
https://github.com/psi-probe/psi-probe/issues/64#issuecomment-425893640

and documented it here on the wiki page:
https://github.com/psi-probe/psi-probe/wiki/Troubleshooting#debian-9-ubuntu-with-openjdk

I hope it was ok...
