### ISSUE TITLE
Error message on log4j2 ConsoleAppender 

### ISSUE THREAD

**Issue by umishu** [psi-probe/psi-probe#1187]
Im using tomcat8.5 with log4j2 on docker container, enable ConsoleAppender for docker log. showing error logs to probe.log on access to probe web application.
I hope exclude to call "getFileName" on ConsoleAppender 

18:21:45.293 ERROR {http-nio-8080-exec-6} [psiprobe.tools.logging.DefaultAccessor] 
java.lang.NoSuchMethodException: No such accessible method: getFileName() on object: org.apache.logging.log4j.core.appender.ConsoleAppender
	at org.apache.commons.lang3.reflect.MethodUtils.invokeMethod(MethodUtils.java:224)
	at org.apache.commons.lang3.reflect.MethodUtils.invokeMethod(MethodUtils.java:256)
	at org.apache.commons.lang3.reflect.MethodUtils.invokeMethod(MethodUtils.java:95)
	at psiprobe.tools.logging.DefaultAccessor.invokeMethod(DefaultAccessor.java:129)
	at psiprobe.tools.logging.log4j2.Log4J2AppenderAccessor.getFile(Log4J2AppenderAccessor.java:79)
	at psiprobe.beans.LogResolverBean$LogDestinationComparator.convertToString(LogResolverBean.java:714)
	at psiprobe.beans.LogResolverBean$AbstractLogComparator.compare(LogResolverBean.java:677)
	at psiprobe.beans.LogResolverBean$AbstractLogComparator.compare(LogResolverBean.java:665)

**Comment by hazendaz** [comment]
Which version of psi probe are you using?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by umishu** [comment]
I am using psi-probe version 3.1.0 (deploy war)
Docker image is tomcat:8.5.31-jre8-slim

**Comment by hazendaz** [comment]
@umishu I presume it actually works though based on the logic.  Yes it throws that exception in the file but so do the other methods of getting at loggers just not as high of importance.  I can make some adjustments here but suspect this is working as-is.  Can you confirm?

**Comment by hazendaz** [comment]
old ticket, much has changed since, if still an issue please open new ticket.
