### ISSUE TITLE
issue should not be possible 

### ISSUE THREAD

**Issue by akinom** [psi-probe/psi-probe#1195]
problem with showing servlets for webapp /rt4ds 

**OS INFORMATION**

jvm:  OpenJDK Runtime Environment  1.7.0_181-mockbuild_2018_05_21_16_38-b00  OpenJDK 64-Bit Server VM) 
os: Linux (unknown) amd64 3.10.0-862.3.2.el7.x86_64
processors: 1

**here is the stack trace** 

org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.NoSuchMethodError: org.apache.catalina.core.StandardWrapper.isSingleThreadModel()Z
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:924)
	at com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:65)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:603)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:542)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:905)
	at org.apache.jsp.WEB_002dINF.jsp.servlets_jsp._jspService(servlets_jsp.java:184)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:410)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:236)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:257)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1183)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:902)
	at com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:65)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:399)
	at org.springframework.security.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)
	at org.springframework.security.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
	at org.springframework.security.ui.ExceptionTranslationFilter.doFilterHttp(ExceptionTranslationFilter.java:101)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
	at org.springframework.security.ui.logout.LogoutFilter.doFilterHttp(LogoutFilter.java:89)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
	at org.springframework.security.ui.preauth.AbstractPreAuthenticatedProcessingFilter.doFilterHttp(AbstractPreAuthenticatedProcessingFilter.java:69)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
	at org.springframework.security.context.HttpSessionContextIntegrationFilter.doFilterHttp(HttpSessionContextIntegrationFilter.java:235)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
	at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:188)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:236)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:615)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:44)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.apache.catalina.core.StandardWrapper.isSingleThreadModel()Z
	at com.googlecode.psiprobe.tools.ApplicationUtils.getServletInfo(ApplicationUtils.java:347)
	at com.googlecode.psiprobe.tools.ApplicationUtils.getApplicationServlets(ApplicationUtils.java:358)
	at com.googlecode.psiprobe.controllers.servlets.ListServletsController.handleContext(ListServletsController.java:52)
	at com.googlecode.psiprobe.controllers.ContextHandlerController.handleRequestInternal(ContextHandlerController.java:40)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
	... 87 more

**web.xml**

<?xml version="1.0" encoding="ISO-8859-1" ?>

		
<!DOCTYPE web-app PUBLIC "-//Sun Microsystems, Inc.//DTD Web Application 2.3//EN"
        "http://java.sun.com/dtd/web-app_2_3.dtd">

<web-app>

    <display-name>DSpace Symplectic Connector</display-name>

    

	
    <context-param>
        <param-name>dspace-config</param-name>
        <param-value>/dspace/rt4ds/config/dspace.cfg</param-value>
        <description>
            The location of the main DSpace configuration file
        </description>
    </context-param>

    
    <context-param>
        <param-name>dspace.dir</param-name>
        <param-value>/dspace/rt4ds</param-value>
        <description>
            The location of the main DSpace configuration file
        </description>
    </context-param>

    <context-param>
      <param-name>javax.servlet.jsp.jstl.fmt.localizationContext</param-name>
      <param-value>Messages</param-value>
    </context-param>

    <context-param>
      <param-name>contextConfigLocation</param-name>
      <param-value>/WEB-INF/spring/*.xml</param-value>
    </context-param>

	

	<filter>
		<filter-name>encoding-filter</filter-name>
		<filter-class>uk.co.symplectic.elements.servlets.CharacterEncodingFilter</filter-class>
	</filter>

	

	<filter-mapping>
		<filter-name>encoding-filter</filter-name>
		<servlet-name>repository</servlet-name>
	</filter-mapping>

	<filter-mapping>
		<filter-name>encoding-filter</filter-name>
		<servlet-name>file-servlet</servlet-name>
	</filter-mapping>

	<filter-mapping>
		<filter-name>encoding-filter</filter-name>
		<servlet-name>publication-details</servlet-name>
	</filter-mapping>

	<filter-mapping>
		<filter-name>encoding-filter</filter-name>
		<servlet-name>test</servlet-name>
	</filter-mapping>

    
    <listener>
     <listener-class>org.dspace.servicemanager.servlet.DSpaceKernelServletContextListener</listener-class>
    </listener>

	
    <listener>
        <listener-class>
            org.dspace.app.util.DSpaceContextListener
        </listener-class>
    </listener>

    
    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>

    

    <servlet>
        <servlet-name>repository</servlet-name>
        <servlet-class>uk.co.symplectic.repository.dspace.servlets.DSpaceRepositoryServlet</servlet-class>
    </servlet>

	<servlet>
        <servlet-name>file-servlet</servlet-name>
        <servlet-class>uk.co.symplectic.repository.dspace.servlets.DSpaceFileServlet</servlet-class>
    </servlet>

	<servlet>
        <servlet-name>publication-details</servlet-name>
        <servlet-class>uk.co.symplectic.repository.dspace.servlets.DSpaceItemServlet</servlet-class>
    </servlet>

    <servlet>
        <servlet-name>collection-mapping</servlet-name>
        <servlet-class>uk.co.symplectic.repository.dspace.collectionmapping.CollectionMappingServlet</servlet-class>
    </servlet>

	
	<servlet>
        <servlet-name>test</servlet-name>
        <servlet-class>uk.co.symplectic.repository.dspace.servlets.DSpaceTestServlet</servlet-class>
    </servlet>

    

	
    <servlet-mapping>
        <servlet-name>repository</servlet-name>
        <url-pattern>/repository</url-pattern>
    </servlet-mapping>

	<servlet-mapping>
        <servlet-name>publication-details</servlet-name>
        <url-pattern>/publication/*</url-pattern>
    </servlet-mapping>

	

	<servlet-mapping>
        <servlet-name>file-servlet</servlet-name>
        <url-pattern>/file/*</url-pattern>
    </servlet-mapping>

    <servlet-mapping>
        <servlet-name>collection-mapping</servlet-name>
        <url-pattern>/collection-mapping</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>collection-mapping</servlet-name>
        <url-pattern>/collection-mapping/</url-pattern>
    </servlet-mapping>

	
	<servlet-mapping>
        <servlet-name>test</servlet-name>
        <url-pattern>/test/*</url-pattern>
    </servlet-mapping>

    
    <taglib>
      <taglib-uri>http://java.sun.com/jsp/jstl/fmt</taglib-uri>
      <taglib-location>/WEB-INF/fmt.tld</taglib-location>
    </taglib>
</web-app>

**Comment by hazendaz** [comment]
old issue, closing, seems related to possible bad tomcat usage but too old now.
