### ISSUE TITLE
Probe tabs Application, Data Sources and Quick Check not working

### ISSUE THREAD

**Issue by AndersonBS** [psi-probe/psi-probe#1199]
I have a problem trying to run psi-probe v3.1.0 along with my private application on a JDK 1.8.0_181 Tomcat 9 environment. If probe is running alone (without any other application, except for tomcat manager) it works without any problems, but whenever I deploy my private application, probe tabs "Application", "Data Sources" and "Quick Check" stop working and presents the following generic message:

> Application encountered an unexpected error. Please check the Tomcat logs. We will greatly appreciate it if you share the information with us. Sharing this information through our issue tracker or our discussion board will help us find and correct this problem as soon as possible!

By checking probe logs, I can find the following exception:

> 15:22:00.006 ERROR {Probe_Quartz-1} [org.quartz.core.JobRunShell] Job DEFAULT.datasourceStatsJobDetail threw an unhandled Exception: 
org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean] failed; nested exception is java.lang.NoClassDefFoundError: oracle/jdbc/pool/OracleDataSource
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:276)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NoClassDefFoundError: oracle/jdbc/pool/OracleDataSource
	at psiprobe.beans.accessors.OracleDatasourceAccessor.canMap(OracleDatasourceAccessor.java:82)
	at psiprobe.beans.accessors.OracleDatasourceAccessor.getInfo(OracleDatasourceAccessor.java:41)
	at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:163)
	at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:124)
	at psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:219)
	at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:203)
	at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:64)
	at sun.reflect.GeneratedMethodAccessor692.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:280)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
	... 3 common frames omitted
15:22:00.006 ERROR {Probe_Quartz-1} [org.quartz.core.ErrorLogger] Job (DEFAULT.datasourceStatsJobDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean] failed; nested exception is java.lang.NoClassDefFoundError: oracle/jdbc/pool/OracleDataSource
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:276)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
Caused by: java.lang.NoClassDefFoundError: oracle/jdbc/pool/OracleDataSource
	at psiprobe.beans.accessors.OracleDatasourceAccessor.canMap(OracleDatasourceAccessor.java:82)
	at psiprobe.beans.accessors.OracleDatasourceAccessor.getInfo(OracleDatasourceAccessor.java:41)
	at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:163)
	at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:124)
	at psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:219)
	at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:203)
	at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:64)
	at sun.reflect.GeneratedMethodAccessor692.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:280)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
	... 3 common frames omitted

It looks like there is an incompatibility among my application and probe's libraries.

Can anyone help me solve it?

Thanks!

**Comment by hazendaz** [comment]
Add ojdbc driver in tomcat lib and the error will go away.  Due to tight integrations, some jars ultimately will need loaded in tomcat classloader.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
