### ISSUE TITLE
Problem Tomcat 9 

### ISSUE THREAD

**Issue by geraldvaras** [psi-probe/psi-probe#1334]
Hi I downloaded the latest probe.war and deployed it on my Tomcat 9 installation and I get the next errors:

`18:13:25.241 INFO  {main} [p.AwtAppContextClassloaderListener] AwtAppContextClassloaderListener Initialized
18:13:25.245 INFO  {main} [o.s.web.context.ContextLoader] Root WebApplicationContext: initialization started
18:13:26.568 INFO  {main} [psiprobe.beans.LogResolverBean] stdoutFiles [stdout.err, stdout.log, wrapper.log, catalina.out]
18:13:26.995 ERROR {main} [psiprobe.model.stats.StatsCollection] Could not read stats data from 'C:\Program Files\Apache Software Foundation\Tomcat 9.0\work\Catalina\localhost\probe\stats.xml'
com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:126)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103)
	at com.thoughtworks.xstream.io.xml.XppReader.<init>(XppReader.java:63)
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54)
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1347)
	at psiprobe.model.stats.StatsCollection.deserialize(StatsCollection.java:273)
	at psiprobe.model.stats.StatsCollection.afterPropertiesSet(StatsCollection.java:328)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1237)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4680)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5150)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:713)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:929)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1377)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1367)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:902)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:344)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:475)
Caused by: java.io.EOFException: input contained no data
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3003)
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
	at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1410)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
	... 78 common frames omitted`
![imagen](https://user-images.githubusercontent.com/882405/59072896-32c2c380-888a-11e9-8ae4-50f2e9166758.png)

**Comment by hazendaz** [comment]
Is there anything custom about your tomcat setup?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by geraldvaras** [comment]
- Windows Server 2016 Standard 
- Apache Tomcat 9.0.20
- JDK 1.8.0_21

**Comment by hazendaz** [comment]
Can you try a newer jdk?  That one is highly vulnerable version.  I don't know that it will make a huge differnece but jdk 8u60 introduced further changes and I suspect if you are past that and possible on anything abouve update 100 that you might see different results.

Besides that, what I meant by custom was any changes you have made to tomcat.  I test this constantly with tomcat7, 8.5, and 9 with limited configuraton changes over default delivered tomcat and run this on windows 10 and windows 7 with jdks 8 through 11 without any issues.  Most if not all exceptions even in the code base only log and do not prevent usage.  Can you try a tomcat version that is untouched from apache on your machine to see if it simply works?

**Comment by geraldvaras** [comment]
I tried with jdk1.8.0_211,
I got the same result.
The options
1. Applications.
2. Data Sources.
3. Quick Check.
Don't work (See error.png).
Te other options work perfect. (See other.png)
![other](https://user-images.githubusercontent.com/882405/60197401-ec1b1600-9804-11e9-8496-19f3069bd534.png)
![error](https://user-images.githubusercontent.com/882405/60197402-ec1b1600-9804-11e9-8afa-1f34979f7bdd.png)

**Comment by hazendaz** [comment]
Can you try the latest 3.3.0?

**Comment by geraldvaras** [comment]
Hi,
The same problem with 3.3.0.
1. Applications
2. Data Sources.
3. Quick Check.

Don't work
I attach the log for more specific details.
[probe.log](https://github.com/psi-probe/psi-probe/files/3335018/probe.log)

**Comment by hazendaz** [comment]
@geraldvaras This helped out quite a bit.  The issue is most likely that you have used tomcat context.xml or server.xml to configure your datasource as commons dbcp 1 but you have not placed that jar into tomcat lib where it would be required for psi probe to access it.  Try that and I bet it fixes your issue.

As an aside, you should not be using that jar.  Commons dbcp 1 is obsolete and regardless tomcat ships with it's own dbcp copy internally which you should be using.  For tomcat 9, they are on dbcp 2.  With that change made, you won't have to do anything special with any additional libs plus added benefit of using what is already in tomcat.

**Comment by geraldvaras** [comment]
Thank you @hazendaz, This solves the problem.

**Comment by hazendaz** [comment]
Issue solved by user setup.  Closing.
