### ISSUE TITLE
Probe：There was an error on frist visit web page

### ISSUE THREAD

**Issue by Rwensy** [psi-probe/psi-probe#1557]
After deploy probe.war in Tomcat vesion 7.0.x ，i visit http://ip:port/probe inputing username and password, but i got a  "There was an error" page information. 

I get logs for details:

18:27:04.927 ERROR {Probe_Quartz-5} [org.quartz.core.ErrorLogger] Job (DEFAULT.connectorStatsJobDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.ConnectorStatsCollectorBean] failed; nested exception is java.lang.NullPointerException
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:276)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
Caused by: java.lang.NullPointerException: null
	at psiprobe.beans.ContainerListenerBean.initialize(ContainerListenerBean.java:146)
	at psiprobe.beans.ContainerListenerBean.getConnectors(ContainerListenerBean.java:290)
	at psiprobe.beans.stats.collectors.ConnectorStatsCollectorBean.collect(ConnectorStatsCollectorBean.java:48)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:280)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
	... 3 common frames omitted

**Comment by hazendaz** [comment]
Which version are you using?  Which tomcat 7 update as well?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Rwensy** [comment]
I download and use both 3.3.0 and 3.31, them occuer same problem. 
Other,  i try it on tomcat 8.0.53, so pity！

**Comment by Rwensy** [comment]
I already run probe 3.3x on cleanly Tomcat ，“There was an error ” problem may be occur in deploy environment，i don't kown reason what happen. Please close this.
