### ISSUE TITLE
Getting error while run in Tomcat 9

### ISSUE THREAD

**Issue by visva2005** [psi-probe/psi-probe#1629]
Getting Below Errro only when we run the application by adding database connection as below.

  <Resource name="jdbc" 
        auth="Container" 
        type="javax.sql.DataSource"
        factory="com.zaxxer.hikari.HikariJNDIFactory"
        minimumIdle="5"
    	maximumPoolSize="300"
        connectionTimeout="300000"
    	maxTotal="100" 
        maxIdle="30" 
        maxWaitMillis="10000"
    	removeAbandonedOnBorrow="true" 
        removeAbandonedTimeout="60" 
        logAbandoned="true"
        dataSource.implicitCachingEnabled="true" 
        dataSourceClassName="oracle.jdbc.pool.OracleDataSource"
      	dataSource.user=""
     	dataSource.password=""
      	dataSource.url="" />  

-----------------------------------------ERROR LOG-----------------------------------

13-Jun-2020 11:05:18.064 INFO [main] org.apache.catalina.core.ApplicationContext.log 1 Spring WebApplicationInitializers detected on classpath
13-Jun-2020 11:05:18.251 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
13-Jun-2020 11:05:24.774 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring ProbeServlet 'probe'
13-Jun-2020 11:05:34.661 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
13-Jun-2020 11:05:34.661 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
13-Jun-2020 11:05:34.664 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@3a1a08f9')
13-Jun-2020 11:06:30.213 SEVERE [http-nio-9101-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [probe] in context with path [/probe] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
	java.lang.NullPointerException
		at psiprobe.beans.LogResolverBean.interrogateContext(LogResolverBean.java:286)
		at psiprobe.beans.LogResolverBean.getAllLogDestinations(LogResolverBean.java:206)
		at psiprobe.beans.LogResolverBean.getLogDestinations(LogResolverBean.java:113)
		at psiprobe.controllers.logs.ListLogsController.handleRequestInternal(ListLogsController.java:88)
		at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
		at psiprobe.controllers.logs.ListLogsController.handleRequest(ListLogsController.java:80)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
		at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
		at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
		at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
		at psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:82)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
		at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
		at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
		at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
		at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
		at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:124)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
		at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
		at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
		at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
		at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
		at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
		at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:666)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at psiprobe.Tomcat90AgentValve.invoke(Tomcat90AgentValve.java:35)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
13-Jun-2020 11:07:35.952 INFO [main] org.apache.catalina.core.ApplicationContext.log 1 Spring WebApplicationInitializers detected on classpath
13-Jun-2020 11:07:36.017 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
13-Jun-2020 11:07:38.834 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring ProbeServlet 'probe'
13-Jun-2020 11:07:46.981 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
13-Jun-2020 11:07:46.981 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
13-Jun-2020 11:07:46.983 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@1389e498')

**Comment by hazendaz** [comment]
@visva2005 Need details on your setup and how you run into that.  This works fine on all tomcats.  i regularly test it.  Custom setups can cause issues if not allowing this solution to have access to all.  Pull requests are always welcome in case of new issue that is not accounted for or coded for.

**Comment by visva2005** [comment]
@hazendaz Thanks for your update.  Just able to re-produce and fixed.
NullPointer exception happening when i put the context URL as "http://localhost:9090/probe". After I changed the redirection in index.jsp its works for me.

<%@ page contentType="text/html;charset=UTF-8" language="java" session="false" %><jsp:forward page="/sysinfo.htm"/>

Instead 

<%@ page contentType="text/html;charset=UTF-8" language="java" session="false" %><jsp:forward page="/index.htm"/>

**Comment by hazendaz** [comment]
closing as issue addressed.
