### ISSUE TITLE
Exception in thread "Probe_Quartz-2" java.lang.NoClassDefFoundError: ch/qos/logback/core/status/WarnStatus

### ISSUE THREAD

**Issue by ivanlbb** [psi-probe/psi-probe#1709]
Hi, I´m running 3.0.1-SNAPSHOT version on Tomcat 8.5.20. 

probe.log file shows this
18:40:00.003 ERROR {Probe_Quartz-5} [org.quartz.core.JobRunShell] Job DEFAULT.datasourceStatsJobDetail threw an unhandled Exception: 
org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean] failed; nested exception is java.lang.NoSuchMethodError: org.apache.catalina.Context.getNamingResources()Lorg/apache/catalina/deploy/NamingResources;
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:276)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NoSuchMethodError: org.apache.catalina.Context.getNamingResources()Lorg/apache/catalina/deploy/NamingResources;
	at psiprobe.Tomcat70ContainerAdapter.addContextResource(Tomcat70ContainerAdapter.java:115)
	at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:117)
	at psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:219)
	at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:203)
	at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:280)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
	... 3 common frames omitted

Thanks in advance

**Comment by hazendaz** [comment]
sounds like you have mixed logback versions.  Also you are on a really old copy which is rather vulnerable at this point.  You might want to concider using the latest tomcat builds and latest of this project.

**Comment by ivanlbb** [comment]
finally I´ve solved it installing 3.0.0.RC1 and forcing the adaptor to my tomcat version as described at https://github.com/psi-probe/psi-probe/wiki/Troubleshooting#error-on-first-request
