### ISSUE TITLE
Graphs not Rendering | Tomcat7DbcpDatasourceAccessor not found

### ISSUE THREAD

**Issue by earlraneses** [psi-probe/psi-probe#2305]
psi-probe-web3.6.0
Tomcat9.0.65
OpenJDK1.8.0_342 (headless)
-Djava.awt.headless=true
RHEL8.4

I'm not getting any graphs and I do not have anything in the logs except those that are about Tomcat7DbcpDatasourceAccessor not found. By any chance, could this cause the graphs to not render?

> 19:09:20.078 ERROR {http-nio-8080-exec-6} [psiprobe.beans.ResourceResolverBean] Failed to lookup: 'UserDatabase'
java.lang.ClassNotFoundException: psiprobe.beans.accessors.Tomcat7DbcpDatasourceAccessor
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1412)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:161)
        at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:84)
        at psiprobe.beans.ContainerWrapperBean.getGlobalDataSources(ContainerWrapperBean.java:239)
        at psiprobe.controllers.datasources.ListAllJdbcResourcesController.handleRequestInternal(ListAllJdbcResourcesController.java:49)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
        at psiprobe.controllers.datasources.ListAllJdbcResourcesController.handleRequest(ListAllJdbcResourcesController.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070)
        at psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:146)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:660)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at psiprobe.Tomcat90AgentValve.invoke(Tomcat90AgentValve.java:38)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:750)

**Comment by earlraneses** [comment]
@hazendaz thanks for the quick fix (for the tomcat version issue). I did try the latest snapshot distro but I am still not able to display the graphs. Any tips on how to troubleshoot?

By the way, seems that logging is no longer working now. This might be related to upgrading SLF4J to 2.x
Below logs are found in catalina.out when starting tomcat:
> SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/usr/share/apache-tomcat-9.0.65/webapps/probe/WEB-INF/lib/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.

It seems that SLF4J v2.x requires at least version 1.3.x of logback:
https://www.slf4j.org/codes.html#StaticLoggerBinder
https://www.slf4j.org/codes.html#ignoredBindings

Should I log this as a separate issue?

**Comment by hazendaz** [comment]
@earlraneses Fixed that, renovate was not suggesting that one and instead jakarta one we could not use.  Manually updated to 1.3.4, please try again.

**Comment by earlraneses** [comment]
@hazendaz, thanks for the quick turnaround. probe logs are getting written now. one thing to note, though, probe logs are no longer visible in "Logs" tab. I think I saw it displayed on 3.6.0

This might give a clue:
> 11:06:53.325 DEBUG {http-nio-8080-exec-4} [psiprobe.beans.LogResolverBean] Could not resolve logback loggers for 'application "/probe"'
java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1412)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220)
        at psiprobe.tools.logging.logback.LogbackFactoryAccessor.<init>(LogbackFactoryAccessor.java:47)
        at psiprobe.beans.LogResolverBean.interrogateClassLoader(LogResolverBean.java:391)
        at psiprobe.beans.LogResolverBean.interrogateContext(LogResolverBean.java:344)
        at psiprobe.beans.LogResolverBean.getAllLogDestinations(LogResolverBean.java:209)
        at psiprobe.beans.LogResolverBean.getLogDestinations(LogResolverBean.java:116)
        at psiprobe.controllers.logs.ListLogsController.handleRequestInternal(ListLogsController.java:91)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
        at psiprobe.controllers.logs.ListLogsController.handleRequest(ListLogsController.java:83)

**Comment by earlraneses** [comment]
regarding the graphs not rendering, could this be the relevant logs?

> 11:19:12.839 DEBUG {http-nio-8080-exec-1} [o.s.s.w.a.i.FilterSecurityInterceptor] Authorized filter invocation [GET /chart.png?p=memory_usage&sp=Tenured+Gen&xz=228&yz=120&l=false&t=1668741552967] with attributes [ROLE_PROBEUSER, ROLE_POWERUSER, ROLE_POWERUSERPLUS, ROLE_MANAGER, ROLE_MANAGER-GUI]
11:19:12.839 DEBUG {http-nio-8080-exec-1} [o.s.security.web.FilterChainProxy] Secured GET /chart.png?p=memory_usage&sp=Tenured+Gen&xz=228&yz=120&l=false&t=1668741552967
11:19:12.839 DEBUG {http-nio-8080-exec-1} [psiprobe.ProbeServlet] GET "/probe/chart.png?p=memory_usage&sp=Tenured+Gen&xz=228&yz=120&l=false&t=1668741552967", parameters={masked}
11:19:12.839 DEBUG {http-nio-8080-exec-1} [o.s.w.s.m.m.a.RequestMappingHandlerMapping] Mapped to psiprobe.controllers.RenderChartController#handleRequest(HttpServletRequest, HttpServletResponse)
11:19:12.841 DEBUG {http-nio-8080-exec-1} **[psiprobe.ProbeServlet] Failed to complete request: java.lang.NullPointerException**
11:19:12.841 DEBUG {http-nio-8080-exec-1} [o.s.s.w.c.SecurityContextPersistenceFilter] Cleared SecurityContextHolder to complete request

**Comment by hazendaz** [comment]
@earlraneses On logs not showing, the master is currently on slf4j 2 which is not yet supported here.  I'm looking into that but in meantime you can simply set slf4j to 1.7.36 and logback to 1.2.11 and it should again display that one.

**Comment by hazendaz** [comment]
@earlraneses Master now supports Slf4j 2 and Logback 1.3 / 1.4 streams for both the core support libraries and variation with TomcatSlf4jLogback juli logger.

**Comment by hazendaz** [comment]
psi probe 3.7.0 has been released, please recheck.

**Comment by hazendaz** [comment]
issues appear previously addressed, closing.
