### ISSUE TITLE
psi-probe causing JVM crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#289]
```
May 10, 2012 6:01:40 PM 
com.googlecode.psiprobe.tools.logging.jdk.Jdk14ManagerAccessor getHandlers
SEVERE: org.apache.juli.ClassLoaderLogManager@26eeda37.getLoggerNames() failed
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:793)
    at java.util.HashMap$KeyIterator.next(HashMap.java:828)
    at java.util.Collections$1.nextElement(Collections.java:3389)
    at com.googlecode.psiprobe.tools.logging.jdk.Jdk14ManagerAccessor.getHandlers(Jdk14ManagerAccessor.java:59)
    at com.googlecode.psiprobe.beans.LogResolverBean.interrogateClassLoader(LogResolverBean.java:253)
    at com.googlecode.psiprobe.beans.LogResolverBean.interrogateApplicationClassLoaders(LogResolverBean.java:235)
    at com.googlecode.psiprobe.beans.LogResolverBean.getAllLogDestinations(LogResolverBean.java:143)
    at com.googlecode.psiprobe.beans.LogResolverBean.getLogDestinations(LogResolverBean.java:68)
    at com.googlecode.psiprobe.controllers.logs.ListLogsController.handleRequestInternal(ListLogsController.java:45)
    at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
    at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
    at com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:54)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:118)
    at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:581)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:999)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:565)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:619)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (synchronizer.cpp:1802), pid=4006, tid=140720366020352
#  Error: guarantee(mid->header()->is_neutral(),"invariant")
#
# JRE version: 6.0_17-b04
# Java VM: Java HotSpot(TM) 64-Bit Server VM (14.3-b01 mixed mode linux-amd64 )
# An error report file with more information is saved as:
# /tmp/hs_err_pid4006.log
#
# If you would like to submit a bug report, please visit:
#   http://java.sun.com/webapps/bugreport/crash.jsp
#

```

Original issue reported on code.google.com by `12all...@gmail.com` on 10 May 2012 at 4:25

**Comment by hazendaz** [comment]
Others use centos without issue with psi probe these days so closing this as no longer an issue.
