### ISSUE TITLE
Unable to view / download JBoss server.log

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#298]
```
Installing psi-probe-2.3.1.zip in JBoss-4.0.3-SP1 produces

2012-07-03 14:02:22,603 INFO  [org.jboss.web.tomcat.tc5.TomcatDeployer] deploy, 
ctxPath=/probe, warUrl=.../tmp/deploy/tmp7526712840690541340probe.war/
2012-07-03 14:02:22,666 INFO  [STDOUT] log4j:ERROR A 
"org.jboss.logging.util.OnlyOnceErrorHandler" object is not assignable to a 
"org.apache.log4j.spi.ErrorHandler" variable.
2012-07-03 14:02:22,666 INFO  [STDOUT] log4j:ERROR The class 
"org.apache.log4j.spi.ErrorHandler" was loaded by
2012-07-03 14:02:22,667 INFO  [STDOUT] log4j:ERROR [WebappClassLoader^M
  delegate: false^M
  repositories:^M
    /WEB-INF/classes/^M
----------> Parent Classloader:^M
java.net.FactoryURLClassLoader@5679bca4^M
] whereas object of type
2012-07-03 14:02:22,667 INFO  [STDOUT] log4j:ERROR 
"org.jboss.logging.util.OnlyOnceErrorHandler" was loaded by 
[org.jboss.system.server.NoAnnotationURLClassLoader@5cac6a45].
2012-07-03 14:02:22,684 INFO  [STDOUT] log4j:ERROR Could not create an 
Appender. Reported error follows.
2012-07-03 14:02:22,684 INFO  [STDOUT] java.lang.ClassCastException: 
org.jboss.logging.appender.DailyRollingFileAppender cannot be cast to 
org.apache.log4j.Appender
2012-07-03 14:02:22,684 INFO  [STDOUT]  at 
org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:175)
......
......
2012-07-03 14:02:22,685 INFO  [STDOUT]  at 
org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java
:468)
2012-07-03 14:27:14,775 INFO  [STDOUT] log4j:ERROR Could not parse url 
[file:/usr/local/jboss/server/default/conf/log4j.xml].
2012-07-03 14:27:14,775 INFO  [STDOUT] java.lang.NullPointerException
2012-07-03 14:27:14,775 INFO  [STDOUT]  at 
java.util.Hashtable.put(Hashtable.java:394)
2012-07-03 14:27:14,782 INFO  [STDOUT]  at org.jboss.Main.boot(Main.java:187)
2012-07-03 14:27:14,782 INFO  [STDOUT]  at org.jboss.Main$1.run(Main.java:438)
2012-07-03 14:27:14,782 INFO  [STDOUT]  at java.lang.Thread.run(Thread.java:662)
......

What steps will reproduce the problem?
1. Copy the probe.war as describe in the installation manaul
2. Start JBoss

What is the expected result?
probe.log should be generated and able to download server.log from WEB-UI.

What happens instead?
Access the server.log produces:
The page you requested does not exist on this server. Please use the navigation 
bar to locate the area you require. 
and the errors as shown above

What version of Probe are you using?
probe-2.3.1

What environment (browser version, Tomcat version, JVM version, server OS)?
OS: CentOS 5.5 64bit
JDK: 1.6.0_22-b04 - 64bit
JBoss: 4.0.3SP1

Please provide any additional information below.


```

Original issue reported on code.google.com by `mas...@gmail.com` on 3 Jul 2012 at 9:04

**Comment by hazendaz** [comment]
closing as log related and on unsupported software versions.  any new logging issues should be tracked against the logging ticket that is pinned.
