### ISSUE TITLE
NullPointerException when accessing app list

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#350]
```
What steps will reproduce the problem?
1.Use Tomcat 7.0.39 Manager App to deploy probe.war (2.3.3)
2.Access probe, entered username and password
3.Error displayed

What is the expected result?
List of the applications

What happens instead?
Got the below error.

org.springframework.web.util.NestedServletException: Request processing failed; 
nested exception is java.lang.NullPointerException at 
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet
.java:583) at 
org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501
) at javax.servlet.http.HttpServlet.service(HttpServlet.java:621) at 
javax.servlet.http.HttpServlet.service(HttpServlet.java:728) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:305) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:210) at 
com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:59)
 at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:243) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:210) at 
org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java
:749) at 
org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatc
her.java:487) at 
org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.j
ava:412) at 
org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.jav
a:339) at 
org.apache.jasper.runtime.PageContextImpl.doForward(PageContextImpl.java:746) 
at org.apache.jasper.runtime.PageContextImpl.forward(PageContextImpl.java:716) 
at org.apache.jsp.index_jsp._jspService(index_jsp.java:63) at 
org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) at 
javax.servlet.http.HttpServlet.service(HttpServlet.java:728) at 
org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432) 
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390) at 
org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334) at 
avax.servlet.http.HttpServlet.service(HttpServlet.java:728) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:305) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:210) at 
com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.jav
a:129) at 
com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
 at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:243) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:210) at 
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:2
22) at 
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:1
23) at 
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.jav
a:581) at 
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) 
at 
com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38) 
at 
org.apache.catalina.ha.session.JvmRouteBinderValve.invoke(JvmRouteBinderValve.ja
va:219) at 
org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:333) 
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) 
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947) at 
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118
) at 
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) at 
org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor
.java:1009) at 
org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractPro
tocol.java:589) at 
org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
 at 
java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:8
86) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) 
at java.lang.Thread.run(Thread.java:662) Caused by: 
java.lang.NullPointerException at 
com.googlecode.psiprobe.tools.ApplicationUtils.getApplication(ApplicationUtils.j
ava:81) at 
com.googlecode.psiprobe.controllers.apps.ListWebappsController.handleRequestInte
rnal(ListWebappsController.java:53) at 
org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractCon
troller.java:153) at 
org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(Simple
ControllerHandlerAdapter.java:48) at 
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.j
ava:875) at 
com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:54) at 
org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.ja
va:807) at 
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet
.java:571) ... 44 more 

What version of Probe are you using?
2.3.3

What environment (browser version, Tomcat version, JVM version, server OS)?
Solaris, Tomcat 7.0.39, JDK 1.6


Please provide any additional information below.
(Attach logs or stack traces as files instead of pasting the contents
here.)
Works well on my local system  but gives error when deploy on Development 
server.
```

Original issue reported on code.google.com by `dilipkri...@gmail.com` on 3 May 2013 at 7:50

**Comment by hazendaz** [comment]
Never seen this situation.  Closing issue.  It's 3 years old and unlikely to still be present.
