### ISSUE TITLE
psi-probe 4.1.1 (and 4.1.4) - Application deployment - error

### ISSUE THREAD

**Issue by tachtler** [psi-probe/psi-probe#3534]
Hi,

when I try to deploy the ROOT.war - 

```
There was an error

Application encountered an unexpected error. Please check the Tomcat logs. We will greatly appreciate it if you
share the information with us. Sharing this information through our [issue tracker] or our [discussion board] will
help us find and correct this problem as soon as possible!
```
The settings for the Application deployment are:
```
Upload application (basic)
Upload a .war file to the server. If context name is not specified the file name will be used.

Select a .war file to upload *
Browse ROOT.war
Context name (ex. /dummy) 
  x Update the application if it is already deployed
  x Discard "work" directory if exists
  x Precompile JSP pages after application is deployed (could take few minutes)
```
The only error inside the probe.log I can see is:
```
08:20:10.004 ERROR {Probe_Quartz-2} [psiprobe.model.stats.StatsCollection] Could not write stats data to '/usr/share/tomcat9/work/Catalina/localhost/probe/stats.xml'
com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.Collections$SynchronizedRandomAccessList
converter           : com.thoughtworks.xstream.converters.reflection.SerializableConverter
message[1]          : Unable to make private void java.util.Collections$SynchronizedCollection.writeObject(java.io.ObjectOutputStream) throws java.io.IOException accessible: module java.base does not "opens java.util" to unnamed module @7434bd34
converter[1]        : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[2]          : Unable to make field private static final long java.util.Collections$SynchronizedCollection.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @7434bd34
-------------------------------
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:478)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:49)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:80)
	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.marshal(TreeMapConverter.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:83)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1303)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1292)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1280)
	at psiprobe.model.stats.StatsCollection.serialize(StatsCollection.java:265)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:285)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```
**How can I help you to figure out, why it doesn't work?
What can I do to get more Information about the error for you?**

My System: (**Archlinux**)
```
Memory utilization
Current memory usage is  	++++++++++++ 	 16.3% 	 Advise Garbage Collection
Free: 345.24 MB Total: 512.00 MB Max: 1.00 GB
OS information
JVM:  OpenJDK Runtime Environment  17.0.11+9  OpenJDK 64-Bit Server VM)
OS: Linux (**Archlinux**) amd64 6.6.36-1-lts
Processors: 2
Current time: Sat Jul 06 08:24:52 CEST 2024
Working dir: /
Container information
Container: Apache Tomcat/9.0.89-dev
catalina.base: /usr/share/tomcat9
catalina.home: /usr/share/tomcat9
Application base: /usr/share/tomcat9/webapps
Configuration base: /usr/share/tomcat9/conf/localhost
```
I'm using psi-probe for a really long time, and it's so great to have it - Please help me, to solve the problem.

Thank you in advance,
Klaus.

**Comment by hazendaz** [comment]
Make sure your tomcat configuration files are up to date.  Specifically, you need the add opens.  Tomcat added that some time ago.  I haven't checked recently but believe it's still setup there.  I'll try to find the specific file and post here later.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Klaus Tachtler ***@***.***>
Sent: Saturday, July 6, 2024 2:28:24 AM
To: psi-probe/psi-probe ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [psi-probe/psi-probe] psi-probe 4.1.1 (and 4.1.4) - Application deployment - error (Issue #3534)


Hi,

when I try to deploy the ROOT.war -

There was an error

Application encountered an unexpected error. Please check the Tomcat logs. We will greatly appreciate it if you
share the information with us. Sharing this information through our [issue tracker] or our [discussion board] will
help us find and correct this problem as soon as possible!


The settings for the Application deployment are:

Upload application (basic)
Upload a .war file to the server. If context name is not specified the file name will be used.

Select a .war file to upload *
Browse ROOT.war
Context name (ex. /dummy)
  x Update the application if it is already deployed
  x Discard "work" directory if exists
  x Precompile JSP pages after application is deployed (could take few minutes)


The only error inside the probe.log I can see is:

08:20:10.004 ERROR {Probe_Quartz-2} [psiprobe.model.stats.StatsCollection] Could not write stats data to '/usr/share/tomcat9/work/Catalina/localhost/probe/stats.xml'
com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.Collections$SynchronizedRandomAccessList
converter           : com.thoughtworks.xstream.converters.reflection.SerializableConverter
message[1]          : Unable to make private void java.util.Collections$SynchronizedCollection.writeObject(java.io.ObjectOutputStream) throws java.io.IOException accessible: module java.base does not "opens java.util" to unnamed module @7434bd34
converter[1]        : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[2]          : Unable to make field private static final long java.util.Collections$SynchronizedCollection.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @7434bd34
-------------------------------
        at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88)
        at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:478)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:49)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
        at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:80)
        at com.thoughtworks.xstream.converters.collections.TreeMapConverter.marshal(TreeMapConverter.java:58)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
        at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:83)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
        at com.thoughtworks.xstream.XStream.marshal(XStream.java:1303)
        at com.thoughtworks.xstream.XStream.marshal(XStream.java:1292)
        at com.thoughtworks.xstream.XStream.toXML(XStream.java:1280)
        at psiprobe.model.stats.StatsCollection.serialize(StatsCollection.java:265)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:285)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)


How can I help you to figure out, why it doesn't work?
What can I do to get more Information about the error for you?

My System: (Archlinux)

Memory utilization
Current memory usage is         ++++++++++++     16.3%   Advise Garbage Collection
Free: 345.24 MB Total: 512.00 MB Max: 1.00 GB
OS information
JVM:  OpenJDK Runtime Environment  17.0.11+9  OpenJDK 64-Bit Server VM)
OS: Linux (**Archlinux**) amd64 6.6.36-1-lts
Processors: 2
Current time: Sat Jul 06 08:24:52 CEST 2024
Working dir: /
Container information
Container: Apache Tomcat/9.0.89-dev
catalina.base: /usr/share/tomcat9
catalina.home: /usr/share/tomcat9
Application base: /usr/share/tomcat9/webapps
Configuration base: /usr/share/tomcat9/conf/localhost


I'm using psi-probe for a really long time, and it's so great to have it - Please help me, to solve the problem.

Thank you in advance,
Klaus.

**Comment by hazendaz** [comment]
clone this locally https://github.com/hazendaz/tomcat9-config and run mvn clean install, then check in the target folder to tomcat-config/apache-tomcat-9.0.91\bin\catalina.sh.  That is verbatim from tomcat.  Make sure to pay attention to the add opens.  Since its clear that is missing, I would suspect many other things too so best to do a full comparison.

Anyway, this is what tomcat has in there in regards to the error here

```
# Add the JAVA 9 specific start-up parameters required by Tomcat
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.base/java.lang=ALL-UNNAMED"
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.base/java.io=ALL-UNNAMED"
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.base/java.util=ALL-UNNAMED"
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.base/java.util.concurrent=ALL-UNNAMED"
JDK_JAVA_OPTIONS="$JDK_JAVA_OPTIONS --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED"
```

**Comment by hazendaz** [comment]
closing as issue is a configuration issue with being in sync with changes tomcat is making to tomcats configuration files.
