### ISSUE TITLE
does not implement the NamespaceHandler interface

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#370]
```
Hi,

probe dont' work and print this message :

---
Unexpected exception parsing XML document from ServletContext resource 
[/WEB-INF/spring-probe-stats.xml]; nested exception is 
java.lang.IllegalArgumentException: Class 
[org.springmodules.cache.config.jboss.JbossCacheNamespaceHandler] does not 
implement the NamespaceHandler 
interfaceorg.springframework.beans.factory.BeanDefinitionStoreException: 
Unexpected exception parsing XML document from ServletContext resource 
[/WEB-INF/spring-probe-stats.xml]; nested exception is 
java.lang.IllegalArgumentException: Class 
[org.springmodules.cache.config.jboss.JbossCacheNamespaceHandler] does not 
implement the NamespaceHandler interface Caused by: 
java.lang.IllegalArgumentException: Class 
[org.springmodules.cache.config.jboss.JbossCacheNamespaceHandler] does not 
implement the NamespaceHandler interface at 
org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.initHandle
rMappings(DefaultNamespaceHandlerResolver.java:119) at 
org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.(DefaultNa
mespaceHandlerResolver.java:96) at 
org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.(DefaultNa
mespaceHandlerResolver.java:82) at 
org.springframework.beans.factory.xml.XmlBeanDefinitionReader.createDefaultNames
paceHandlerResolver(XmlBeanDefinitionReader.java:530) at 
org.springframework.beans.factory.xml.XmlBeanDefinitionReader.createReaderContex
t(XmlBeanDefinitionReader.java:519) at 
org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefini
tions(XmlBeanDefinitionReader.java:499) at 
org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefiniti
ons(XmlBeanDefinitionReader.java:407) at 
org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinition
s(XmlBeanDefinitionReader.java:357) at 
org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinition
s(XmlBeanDefinitionReader.java:334) at 
org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanD
efinitions(AbstractBeanDefinitionReader.java:126) at 
org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanD
efinitions(AbstractBeanDefinitionReader.java:142) at 
org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinit
ions(XmlWebApplicationContext.java:123) at 
org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinit
ions(XmlWebApplicationContext.java:91) at 
org.springframework.context.support.AbstractRefreshableApplicationContext.refres
hBeanFactory(AbstractRefreshableApplicationContext.java:94) at 
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractA
pplicationContext.java:292) at 
org.springframework.web.context.support.AbstractRefreshableWebApplicationContext
.refresh(AbstractRefreshableWebApplicationContext.java:156) at 
org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(Fra
meworkServlet.java:308) at 
org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(Frame
workServlet.java:252) at 
org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServle
t.java:221) at 
org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:115) 
at javax.servlet.GenericServlet.init(GenericServlet.java:212) at 
org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1173) 
at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:809) 
at 
org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java
:615) at 
org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatc
her.java:436) at 
org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.j
ava:374) at 
org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.jav
a:302) at 
org.apache.jasper.runtime.PageContextImpl.doForward(PageContextImpl.java:706) 
at org.apache.jasper.runtime.PageContextImpl.forward(PageContextImpl.java:677) 
at jsp.index_jsp._jspService(jsp.index_jsp:43) at 
org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) at 
javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:290) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:118
) at 
com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:52) 
at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:2
33) at 
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:1
91) at 
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.jav
a:558) at 
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) 
at 
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) 
at 
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109
) at 
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298) at 
org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190) at 
org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291) at 
org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:769) at 
org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:698) at 
org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:891
) at 
org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:69
0) at java.lang.Thread.run(Thread.java:662) Caused by: 
java.lang.IllegalArgumentException: Class 
[org.springmodules.cache.config.jboss.JbossCacheNamespaceHandler] does not 
implement the NamespaceHandler interface at 
org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.initHandle
rMappings(DefaultNamespaceHandlerResolver.java:119) at 
org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.(DefaultNa
mespaceHandlerResolver.java:96) at 
org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.(DefaultNa
mespaceHandlerResolver.java:82) at 
org.springframework.beans.factory.xml.XmlBeanDefinitionReader.createDefaultNames
paceHandlerResolver(XmlBeanDefinitionReader.java:530) at 
org.springframework.beans.factory.xml.XmlBeanDefinitionReader.createReaderContex
t(XmlBeanDefinitionReader.java:519) at 
org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefini
tions(XmlBeanDefinitionReader.java:499) at 
org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefiniti
ons(XmlBeanDefinitionReader.java:407) at 
org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinition
s(XmlBeanDefinitionReader.java:357) at 
org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinition
s(XmlBeanDefinitionReader.java:334) at 
org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanD
efinitions(AbstractBeanDefinitionReader.java:126) at 
org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanD
efinitions(AbstractBeanDefinitionReader.java:142) at 
org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinit
ions(XmlWebApplicationContext.java:123) at 
org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinit
ions(XmlWebApplicationContext.java:91) at 
org.springframework.context.support.AbstractRefreshableApplicationContext.refres
hBeanFactory(AbstractRefreshableApplicationContext.java:94) at 
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractA
pplicationContext.java:292) at 
org.springframework.web.context.support.AbstractRefreshableWebApplicationContext
.refresh(AbstractRefreshableWebApplicationContext.java:156) at 
org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(Fra
meworkServlet.java:308) at 
org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(Frame
workServlet.java:252) at 
org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServle
t.java:221) at 
org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:115) 
at javax.servlet.GenericServlet.init(GenericServlet.java:212) at 
org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1173) 
at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:809) 
at 
org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java
:615) at 
org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatc
her.java:436) at 
org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.j
ava:374) at 
org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.jav
a:302) at 
org.apache.jasper.runtime.PageContextImpl.doForward(PageContextImpl.java:706) 
at org.apache.jasper.runtime.PageContextImpl.forward(PageContextImpl.java:677) 
at jsp.index_jsp._jspService(jsp.index_jsp:43) at 
org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) at 
javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:290) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:118
) at 
com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:52) 
at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:2
33) at 
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:1
91) at 
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.jav
a:558) at 
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) 
at 
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) 
at 
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109
) at 
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298) at 
org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190) at 
org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291) at 
org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:769) at 
org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:698) at 
org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:891
) at 
org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:69
0) at java.lang.Thread.run(Thread.java:662)

---

What is the expected result?


What happens instead?


version of Probe : 2.0.2


browser version : mozilla firefox 23
Tomcat version : 6.0.24-57.el6_4
JVM version : sun version 1.6.0_31
server OS : redhat RHEL 6.4 santiago
kernel : 2.6.32-358.14.1.el6.x86_64

```

Original issue reported on code.google.com by `ipsyk...@gmail.com` on 22 Aug 2013 at 3:24

**Comment by hazendaz** [comment]
Closing as this was for tomcat6 and we are no longer supporting that.
