### ISSUE TITLE
Deployment fails using probe screen

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#373]
```
What steps will reproduce the problem?
1.Deploy the application using psi-probe war from windows desktop on to remote 
Linux machine where tomcat instance is running &probe is deployed on that


What is the expected result?
deploy should be successful

What happens instead?
Deployment fails & below exception is getting reported in the logs 

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR com.googlecode.psiprobe.controllers.deploy.UploadWarController  - Could 
not process file upload
org.apache.commons.fileupload.FileUploadException: Read timed out
        at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:369)
        at org.apache.commons.fileupload.servlet.ServletFileUpload.parseRequest(ServletFileUpload.java:126)
        at com.googlecode.psiprobe.controllers.deploy.UploadWarController.handleRequestInternal(UploadWarController.java:57)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
        at com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:54)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:511)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:581)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

What version of Probe are you using?
2.3.3

What environment (browser version, Tomcat version, JVM version, server OS)?
jvm - 1.7
Tomcat -7.0
OS - Linux 6

Please provide any additional information below.
(Attach logs or stack traces as files instead of pasting the contents
here.)

```

Original issue reported on code.google.com by `viveknan...@gmail.com` on 7 Sep 2013 at 4:24

**Comment by hazendaz** [comment]
Closing issue.  Never seen this occur and this is how we run things.  Works like expected.  No further user imput since original issue.  Since there are known issues around successful WAR but not displaying results, it's pretty safe to say this is not an issue.
