### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class sun.font.FontScaler

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#375]
```
When apache tomcat starts I got this in log:

SEVERE: Servlet.service() for servlet [probe] in context with path [/probe] 
threw exception [Handler processing failed; nested exception is 
java.lang.NoClassDefFoundError: Could not initialize class sun.font.FontScaler] 
with root cause
java.lang.NoClassDefFoundError: Could not initialize class sun.font.FontScaler
        at sun.font.Type1Font.getScaler(Type1Font.java:638)
        at sun.font.FileFontStrike.<init>(FileFontStrike.java:177)

Something wrong with my java setup?

java -version
java version "1.7.0_40"
Java(TM) SE Runtime Environment (build 1.7.0_40-b43)
Java HotSpot(TM) 64-Bit Server VM (build 24.0-b56, mixed mode)

Apache Tomcat 7.0.42

```

Original issue reported on code.google.com by `zawa...@gmail.com` on 27 Sep 2013 at 1:19

**Comment by apjkaran89** [comment]
javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class sun.text.normalizer.NormalizerImpl

**Comment by durban77** [comment]
Probably you installed a newer java environment (or just from an other vendor), but you are trying to use the older one. You thought that setting the PATH and JAVA_HOME is just enough for you. Maybe you are trying to use a headless jre running your awt dependent code.
