### ISSUE TITLE
Support for JBoss 8.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#378]
```
What steps will reproduce the problem?
1.Start Jboss
2. deploy probe-2.3.3
3.

What is the expected result?
Failed deploy

What happens instead?
Failed deploy


What version of Probe are you using?
last stable


What environment (browser version, Tomcat version, JVM version, server OS)?

JBoss Bootstrap Environment

  JBOSS_HOME: /home/mino/Scrivania/wildfly-8.0.0.Beta1

  JAVA: /home/mino/corsomilanojboss7/jdk1.7.0_09/bin/java

  JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true



Please provide any additional information below.
(Attach logs or stack traces as files instead of pasting the contents
here.)




12:14:14,237 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) 
MSC000001: Failed to start service 
jboss.deployment.unit."probe.war".POST_MODULE: 
org.jboss.msc.service.StartException in service 
jboss.deployment.unit."probe.war".POST_MODULE: JBAS018733: Failed to process 
phase POST_MODULE of deployment "probe.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:166) [wildfly-server-8.0.0.Beta1.jar:8.0.0.Beta1]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1944) [jboss-msc-1.2.0.Beta2.jar:1.2.0.Beta2]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1877) [jboss-msc-1.2.0.Beta2.jar:1.2.0.Beta2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [rt.jar:1.7.0_09]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [rt.jar:1.7.0_09]
	at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_09]
Caused by: java.lang.LinkageError: Failed to link 
com/googlecode/psiprobe/ProbeServlet (Module "deployment.probe.war:main" from 
Service Module Loader)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:428) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:261) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:76) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.Module.loadModuleClass(Module.java:548) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:189) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118) [jboss-modules.jar:1.3.0.Final]
	at java.lang.Class.forName0(Native Method) [rt.jar:1.7.0_09]
	at java.lang.Class.forName(Class.java:264) [rt.jar:1.7.0_09]
	at org.jboss.as.server.deployment.reflect.DeploymentClassIndex.classIndex(DeploymentClassIndex.java:54) [wildfly-server-8.0.0.Beta1.jar:8.0.0.Beta1]
	at org.jboss.as.ee.component.deployers.InterceptorAnnotationProcessor.processComponentConfig(InterceptorAnnotationProcessor.java:85)
	at org.jboss.as.ee.component.deployers.InterceptorAnnotationProcessor.deploy(InterceptorAnnotationProcessor.java:77)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [wildfly-server-8.0.0.Beta1.jar:8.0.0.Beta1]
	... 5 more
Caused by: java.lang.NoClassDefFoundError: org/apache/catalina/ContainerServlet
	at java.lang.ClassLoader.defineClass1(Native Method) [rt.jar:1.7.0_09]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791) [rt.jar:1.7.0_09]
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:345) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:423) [jboss-modules.jar:1.3.0.Final]
	... 19 more
Caused by: java.lang.ClassNotFoundException: 
org.apache.catalina.ContainerServlet from [Module "deployment.probe.war:main" 
from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:443) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:431) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:373) [jboss-modules.jar:1.3.0.Final]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:118) [jboss-modules.jar:1.3.0.Final]
	... 23 more

12:14:14,242 ERROR [org.jboss.as.controller.management-operation] (XNIO-1 
task-8) JBAS014613: Operation ("deploy") failed - address: ([("deployment" => 
"probe.war")]) - failure description: {"JBAS014671: Failed services" => 
{"jboss.deployment.unit.\"probe.war\".POST_MODULE" => 
"org.jboss.msc.service.StartException in service 
jboss.deployment.unit.\"probe.war\".POST_MODULE: JBAS018733: Failed to process 
phase POST_MODULE of deployment \"probe.war\"
    Caused by: java.lang.LinkageError: Failed to link com/googlecode/psiprobe/ProbeServlet (Module \"deployment.probe.war:main\" from Service Module Loader)
    Caused by: java.lang.NoClassDefFoundError: org/apache/catalina/ContainerServlet
    Caused by: java.lang.ClassNotFoundException: org.apache.catalina.ContainerServlet from [Module \"deployment.probe.war:main\" from Service Module Loader]"}}
12:14:14,247 ERROR [org.jboss.as.server] (XNIO-1 task-8) JBAS015870: Deploy of 
deployment "probe.war" was rolled back with the following failure message: 
{"JBAS014671: Failed services" => 
{"jboss.deployment.unit.\"probe.war\".POST_MODULE" => 
"org.jboss.msc.service.StartException in service 
jboss.deployment.unit.\"probe.war\".POST_MODULE: JBAS018733: Failed to process 
phase POST_MODULE of deployment \"probe.war\"
    Caused by: java.lang.LinkageError: Failed to link com/googlecode/psiprobe/ProbeServlet (Module \"deployment.probe.war:main\" from Service Module Loader)
    Caused by: java.lang.NoClassDefFoundError: org/apache/catalina/ContainerServlet
    Caused by: java.lang.ClassNotFoundException: org.apache.catalina.ContainerServlet from [Module \"deployment.probe.war:main\" from Service Module Loader]"}}
12:14:14,308 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) 
JBAS015877: Stopped deployment probe.war (runtime-name: probe.war) in 61ms

```

Original issue reported on code.google.com by `erasmo.m...@gmail.com` on 24 Oct 2013 at 10:18

**Comment by hazendaz** [comment]
I think this issue should be closed.  Wildfly / JBoss 8 and forwards is on an entirely different structure.  Since our core is tomcat 7 based, it won't work on wildfly at all.  Wildfly uses undertow.  I think we would have somewhat better luck on a variation of spring boot than we would trying to make this work on undertow at least in current design.  If we want to go that direction, we need to completely abstract the core away from any specific container.  The the probing modules will figure out the rest.  It's still quite possible to take this beyond tomcat but will probably take a quite a bit of work.

**Comment by MALfunction84** [comment]
Agreed.

**Comment by hazendaz** [comment]
ok - closing for now.

**Comment by diogosantana** [comment]
Do you guys think that any time in the future we should remove all support for JBoss since we won't support the latest?

**Comment by MALfunction84** [comment]
If possible, I'd like to see us move toward something that is server agnostic.

**Comment by jander99** [comment]
This may mean dropping support for certain objects because they aren't
mbeans.  Or trying to architect a plugin solution to provide custom mbean
interfaces.  example would be Loggers or Connectors.
