### ISSUE TITLE
Tomcat 11.0.1 does not come with AbstractHttp11JsseProtocol

### ISSUE THREAD

**Issue by c-m-d-1234** [psi-probe/psi-probe#4037]
looking at the code AbstractHttp11JsseProtocol can be replaced with AbstractHttp11Protocol as it is actually using the AbstractHttp11Protocol interface calls

**Comment by hazendaz** [comment]
@c-m-d-1234 Do you know where that changed?  I tested on much earlier versions of tomcat 11 and it was working.  Probably been 6 months or more though.  If you could contribute a pull request that would be great and even better if you can pinpoint where that was a problem and if it will also work on tomcat 10.

**Comment by Teutron-flo** [comment]
Some informations for the same:

https://github.com/apache/tomcat/commit/0e17fee8571e580ae2fc973ac08e2abf3dc13c9d

https://github.com/apache/tomcat/commit/2b4be933abc1176f1ed684202db8e6a3ef943eb7

**Comment by Teutron-flo** [comment]
In my local project, i did the following changes:

1. Replace AbstractHttp11JsseProtocol with AbstractHttp11Protocol 
2. Updated the common pom to Tomcat 11 instead of 10
3. Inside psiprobe.model.ServletInfo private int errorCount; & private int requestCount; changed to long

The result is now that the application starts on Tomcat 11, but it wants now to have a SSL config in place inside the server.xml.
    <Connector port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol"
               maxThreads="150" SSLEnabled="true">
        <UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" />
        <SSLHostConfig>
            <Certificate certificateKeystoreFile="conf/localhost-rsa.jks"
                         certificateKeystorePassword="changeit" type="RSA" />
        </SSLHostConfig>
    </Connector>

Otherwise you run into:
07-Jan-2025 08:29:42.953 INFO [http-nio-8080-exec-1] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
        java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x060xd20x010x000x060xce0x030x030x920xf10x0d0xf00xba0x9f0xf00xca0xfd0xea0xa3 ]. HTTP method names must be tokens
                at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:395)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:268)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
                at java.base/java.lang.Thread.run(Thread.java:1583)

But still with all the things in place, you get only a white page displayed. No errors in any logs...

I tried already a couple of things here to solve the issues, but I think for the moment I'm runnig out of knowleage here.

**Comment by c-m-d-1234** [comment]
Our testing server is set this way.

`<Connector port="443" 
	    protocol="org.apache.coyote.http11.Http11Nio2Protocol"
        maxThreads="150" SSLEnabled="true" scheme="https" secure="true"
		relaxedPathChars='[]|'
		relaxedQueryChars='[]|{}^&#x5c;&#x60;&quot;&lt;&gt;'
		useSendfile="false"
		compression="on" 
		compressionMinSize="1024"
		compressibleMimeType="text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,font/woff2" >
		<UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" OverheadContinuationThreshold="0" overheadDataThreshold="0" overheadWindowUpdateThreshold="0"/>
        <SSLHostConfig protocols="TLSv1.2+TLSv1.3" honorCipherOrder="true" ciphers="TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_EMPTY_RENEGOTIATION_INFO_SCSVF">
            <Certificate certificateKeyFile="C:\SSL\key.pem"
                         certificateFile="C:\SSL\com.crt"
						 certificateChainFile="C:\SSL\chaincert.pem"
                         type="RSA" />
        </SSLHostConfig>
    </Connector>`

**Comment by hazendaz** [comment]
@Teutron-flo Thanks for the work you did to this point.  Psi probe has required https for a while now.  The other part you ran into requires reflection due to supporting multiple tomcat versions.  I'm working on it now and thinking I will have a solution very soon.

**Comment by hazendaz** [comment]
@Teutron-flo ok I'm now getting same result you are with blank page, no logs.  I'm going to push up what I have most likely though as it works fine with tomcat 10 and expected would need changed for tomcat 11.

**Comment by hazendaz** [comment]
Its possible there are issues in displaytag and other legacy components here.  I ran in debug and everything looks ok but clearly its not logging what is going on and developer view in browser shows no issue other than favicon.  I'll work to release all the other legacy components to see if this can progress at all.

**Comment by hazendaz** [comment]
Found this while debugging it again.

19:20:06.203 DEBUG {catalina-exec-6} [o.a.t.u.n.j.JSSESupport] : Error trying to obtain a certificate from the client
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:1033)
	at org.apache.tomcat.util.net.jsse.JSSESupport.getPeerCertificateChain(JSSESupport.java:107)
	at org.apache.coyote.AbstractProcessor.populateSslRequestAttributes(AbstractProcessor.java:834)
	at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:496)
	at org.apache.coyote.Request.action(Request.java:544)
	at org.apache.catalina.connector.Request.getAttribute(Request.java:875)
	at org.apache.catalina.connector.Request.getAttributeNames(Request.java:950)
	at org.apache.catalina.connector.RequestFacade.getAttributeNames(RequestFacade.java:103)
	at org.apache.catalina.core.ApplicationHttpRequest$AttributeNamesEnumerator.<init>(ApplicationHttpRequest.java:923)
	at org.apache.catalina.core.ApplicationHttpRequest.getAttributeNames(ApplicationHttpRequest.java:273)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:947)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:619)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:716)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:539)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:436)
	at com.opensymphony.sitemesh.compatability.OldDecorator2NewDecorator.render(OldDecorator2NewDecorator.java:66)
	at com.opensymphony.sitemesh.webapp.decorator.BaseWebAppDecorator.render(BaseWebAppDecorator.java:73)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:598)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at psiprobe.Tomcat11AgentValve.invoke(Tomcat11AgentValve.java:38)

**Comment by hazendaz** [comment]
closing this issue as original issue since addressed, opened new issue to continue the current issue as not all tomcat 11 is non supported at the moment.

**Comment by hazendaz** [comment]
tomcat 11 support is back.  See 5.2.0 release for support again.
