### ISSUE TITLE
Tomcat 7.0.54  Psi probe not listing global datasource configured on server.xml

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#411]
```
What steps will reproduce the problem?
1. Download apache-tomcat-7.0.54.tar.gz
2. tar xvf apache-tomcat-7.0.54.tar.gz
3. Change tomcat-users.xml and set manager-gui role on tomcat
5. Place latest mysql connector (mysql-connector-java-5.1.30.jar) inside lib
6. Install psi-probe
7. configure datasource on server.xml by adding inside the 
<GlobalNamingResources> tag 
the configuration

<Resource name="jdbc/test" 
auth="Container"                            
type="javax.sql.DataSource"             
maxActive="4" 
minActive="1" 
maxIdle="2" 
maxWait="10000"
username="username" 
password="password" 
driverClassName="com.mysql.jdbc.Driver"              
url="jdbc:mysql://localhost:3306/test"   
validationQuery="SELECT 1"
testOnBorrow="true" />

What is the expected result?
When I login to probe and go to http://localhost:8080/probe/datasources.htm
I should see the jdbc/test as a global configured datasource


What happens instead?
However the response is 
"There are no data sources configured for this Tomcat instance "

What version of Probe are you using?
2.3.3.

What environment (browser version, Tomcat version, JVM version, server OS)?
Java version Java 1.7.0_51, Tomcat 7.0.54 


Please provide any additional information below.

Considering Tomcat 7.0.54 

If add a resource link on the conf/context.xml file

<ResourceLink type="javax.sql.DataSource"
 name="jdbc/test" global="jdbc/test"/>

Then on the datasources page I see a listing with each application linking to 
the jdbc/test datasource defined on the server.xml (Auth Linking).

Also defining the datasource on the conf/context.xml file is successful too.
I add the same configuration on the conf/context.xml and on the datasources 
page I see a listing with each application having it's own jdbc/test datasource.
 
The exceptions that i get

02 Jun 2014 22:29:04 [http-bio-8000-exec-5] ERROR 
com.googlecode.psiprobe.beans.ResourceResolverBean  - Failed to lookup: 
UserDatabase
javax.naming.NameNotFoundException: Name [UserDatabase] is not bound in this 
Context. Unable to find [UserDatabase].
	at org.apache.naming.NamingContext.lookup(NamingContext.java:819)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:167)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:156)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.googlecode.psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:148)
	at com.googlecode.psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:69)
	at com.googlecode.psiprobe.beans.ContainerWrapperBean.getGlobalDataSources(ContainerWrapperBean.java:183)
	at com.googlecode.psiprobe.controllers.datasources.ListAllJdbcResourcesController.handleRequestInternal(ListAllJdbcResourcesController.java:32)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
	at com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:54)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:744)

02 Jun 2014 22:29:04 [http-bio-8000-exec-5] INFO  
com.googlecode.psiprobe.beans.ResourceResolverBean  - reading resource: 
Catalina:type=Resource,resourcetype=Global,class=javax.sql.DataSource,name="jdbc
/test"
02 Jun 2014 22:29:04 [http-bio-8000-exec-5] ERROR 
com.googlecode.psiprobe.beans.ResourceResolverBean  - Failed to lookup: 
jdbc/protoporia
javax.naming.NameNotFoundException: Name [jdbc/test] is not bound in this 
Context. Unable to find [jdbc].
	at org.apache.naming.NamingContext.lookup(NamingContext.java:819)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:167)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:156)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.googlecode.psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:148)
	at com.googlecode.psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:69)
	at com.googlecode.psiprobe.beans.ContainerWrapperBean.getGlobalDataSources(ContainerWrapperBean.java:183)
	at com.googlecode.psiprobe.controllers.datasources.ListAllJdbcResourcesController.handleRequestInternal(ListAllJdbcResourcesController.java:32)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
	at com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:54)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:744)


As I said this behaviour (not listing global configured datasource on 
server.xml) happens on Tomcat 7.0.54. In other versions that I have tried 
tomcat 7.0.53 and tomcat 7.0.47 global configured datasource (through 
server.xml) is displayed successfully


```

Original issue reported on code.google.com by `gkatzio...@gmail.com` on 2 Jun 2014 at 7:38

**Comment by reinert** [comment]
The guys from Tomcat considered this as a Probe only issue. Here's the log:

>  I don't see any evidence that this issue is related to r1592952. The
only justification for linking them appears to be that psi-probe is
having trouble with JNDI resources and that that commit has something to
do with JNDI.
>  
>  Given the other JNDI related changes listed in the change log, r1592952
isn't the first place I'd look.
>  
>  There have been no reports of applications not being able to look up
Global JNDI resources in the 9 months since 7.0.54 was released. That
suggests that the problem lies with how psi-probe is obtaining the
Global JNDI resources. The Tomcat developers aren't going to start
digging through psi-probe's source to figure out what isn't working.
>  
>  I recommend putting together a simple test case (e.g. single JSP or
Servlet) that demonstrates the problem.
>  
>  Mark
>  
>>  Hi community.
>>  
>>  There's a burning issue going on in project probe-psi triggered by tomcat 7.0.54 release. The issue 411 states about NamingContext lookup that was working properly before the referred tomcat release and since then it doesn't anymore.
>>  
>>  I can't say it's a bug because I didn't investigate deeply, but at least it seems a malfunction.
>>  
>>  There's a suspect the bug was introduced in the commit 1592052 by markt.
>>  
>>  I really would appreciate your help guys.
>>  
>>  Thanks.
>>

**Comment by reinert** [comment]
As a (very ugly dirty) workaround here's what I did to get Probe working properly on Java8: 
1) Install the latest version of Tomcat7
2) Download Tomcat 7.0.53 and extract its content
3) Copy all catalina*.jar and tomcat*.jar to your CATALINA_HOME/lib, overwriting existing jars.

Now you have a mixed installation of latest version with 7.0.53.

Obviously we need to solve this issue the right way urgently.

**Comment by tommytusj** [comment]
I'll have a colleague of mine to take a look. He thinks this is easy to solve. We'll keep you updated this week

**Comment by reinert** [comment]
Appreciated!

**Comment by andresol** [comment]
I have looked into it, and the code that "fails" is ResourceResolverBean:132. 
When it tries to lookup global datasource with java:jdbc/test. This failes. 

The tomcat documentation says:
"These resources are listed in the server's global JNDI resource context. This context is distinct from the per-web-application JNDI contexts described in the JNDI Resources HOW-TO. The resources defined in this element are not visible in the per-web-application contexts unless you explicitly link them with <ResourceLink> elements." 

So I think that this is right behavior for line ResourceResolverBean:132:String jndiName = resolveJndiName("java:jdbc/test");

I have created a patch. Don't know if this is the right way to do it. But it will display it. The javax.naming.NameNotFoundException: Name [UserDatabase] is not bound in this 
Context. Unable to find [UserDatabase] comes from server.xml. Just ignore that. 

```
diff --git a/core/src/main/java/com/googlecode/psiprobe/beans/ResourceResolverBean.java b/core/src/main/java/com/googlecode/psiprobe/beans/ResourceResolverBean.java
index 278b575..9a35d61 100644
--- a/core/src/main/java/com/googlecode/psiprobe/beans/ResourceResolverBean.java
+++ b/core/src/main/java/com/googlecode/psiprobe/beans/ResourceResolverBean.java
@@ -109,7 +109,8 @@
 
             	containerWrapper.getTomcatContainer().addContextResourceLink(context, resourceList, contextBound);
             	for (int i = 0 ; i < resourceList.size() ; i++) {
-            		lookupResource((ApplicationResource) resourceList.get(i), contextBound, false);
+            		ApplicationResource applicationResource = (ApplicationResource) resourceList.get(i);
+            		lookupResource(applicationResource, contextBound, false);
             	}
             	
             } finally {
@@ -128,7 +129,7 @@
         DataSourceInfo dataSourceInfo = null;
         if (contextBound) {
             try {
-                String jndiName = resolveJndiName(resource.getName(), global);
+                String jndiName = resolveJndiName(resource.getName());
                 Object o = new InitialContext().lookup(jndiName);
                 resource.setLookedUp(true);
                 for (Iterator it = datasourceMappers.iterator(); it.hasNext();) {
@@ -172,7 +173,7 @@
             ContextBindings.bindClassLoader(context, null, Thread.currentThread().getContextClassLoader());
         }
         try {
-            String jndiName = resolveJndiName(resourceName, (context == null));
+            String jndiName = resolveJndiName(resourceName);
             Object o = new InitialContext().lookup(jndiName);
             try {
                 for (Iterator it = datasourceMappers.iterator(); it.hasNext();) {
@@ -203,7 +204,7 @@
             ContextBindings.bindClassLoader(context, null, Thread.currentThread().getContextClassLoader());
         }
         try {
-            String jndiName = resolveJndiName(resourceName, (context == null));
+            String jndiName = resolveJndiName(resourceName);
             Object o = new InitialContext().lookup(jndiName);
 
             if (o instanceof DataSource) {
@@ -253,8 +254,8 @@
      * @see #DEFAULT_GLOBAL_RESOURCE_PREFIX
      * @see #DEFAULT_RESOURCE_PREFIX
      */
-    protected static String resolveJndiName(String name, boolean global) {
-        return (global ? DEFAULT_GLOBAL_RESOURCE_PREFIX : DEFAULT_RESOURCE_PREFIX) + name;
+    protected static String resolveJndiName(String name) {
+        return DEFAULT_RESOURCE_PREFIX + name;
     }
 
     private String getStringAttribute(MBeanServer server, ObjectName objectName, String attributeName) {
```

**Comment by MALfunction84** [comment]
The proposed patch would undo many of the changes added in #43 by d9a1d342aa4b69325474d7cc88b082c61237c380. It worked at one time. My concern is that this is behaving differently on different servers.

**Comment by MALfunction84** [comment]
It's possible this patch will address the issues with Tomcat 8 datasources (#394) as well. Can anyone confirm?

@andresol Can you submit a pull request? Applying patches can be slow and error-prone.

**Comment by henry-caballero** [comment]
Managed to solve it by looking at Tomcat sources and now probe lists both global and application resources in Tomcat 8.0.21.

The problem lies in the ```ResourceResolverBean``` not being able to bind to naming contexts, basically because the security check changed and silently fails. Before Tomcat 8.0.6 a ```null``` token worked for binding (the verification was kind of messed) but now the ```NamingContextListener``` and ```StandardContext``` use a new attribute ```namingToken```, so a ```null``` token no longer works. ```ResourceResolverBean``` then operates on probe's own JNDI context and won't look up any resource.

Given the attribute doesn't exist in previous versions I'm getting it through reflection to preserve Tomcat 5.5.23+ compatibility but this forced me to raise JVM to 1.5. Anyway the fix will work for those with newer environments (JVM 1.5+). For global resources, the global JNDI context is now retrieved from the server's ```getGlobalNamingContext()``` method, this way ```java:``` must be omitted.

Here's an overview of the fix:

```
	/**
	 * Returns the security token required to bind to a naming context.
	 *
	 * @param context the catalina context
	 * 
	 * @return the security token for use with <code>ContextBindings</code>
	 */
	protected Object getNamingToken(Context context) {
		
		//null token worked before 8.0.6
		Object token = null;
		if (!ContextAccessController.checkSecurityToken(context, token)) {
			try {
				//namingToken added to Context and Server interfaces in 8.0.6
				//Used by NamingContextListener when settinp up JNDI context
				java.lang.reflect.Method mGetNamingToken = context.getClass().getDeclaredMethod("getNamingToken");
				token = mGetNamingToken.invoke(context);
				
				if (!ContextAccessController.checkSecurityToken(context, token)) {
					logger.error("Couldn't get a valid security token. ClassLoader binding will fail.");
				}
			}
			catch (Exception e) {
				logger.error("There was an error getting namingToken through reflection", e);
			}
		}
		
		return token;
	}
	
    public synchronized List getApplicationResources(Context context, ContainerWrapperBean containerWrapper) throws NamingException {

        List resourceList = new ArrayList();

        boolean contextAvailable = containerWrapper.getTomcatContainer().getAvailable(context);
        if (contextAvailable) {

            logger.info("Reading CONTEXT " + context.getName());

            boolean contextBound = false;
			Object token = getNamingToken(context);
			
            try {
                ContextBindings.bindClassLoader(context, token, Thread.currentThread().getContextClassLoader());
                contextBound = true;
            } catch (NamingException e) {
                logger.error("Cannot bind to context. useNaming=false ?");
                logger.debug("  Stack trace:", e);
            }
	...

	/**
	 * Returns the Server's global naming context
	 *
	 * @return the global JNDI context
	 */
	protected javax.naming.Context getGlobalNamingContext() {
		
		javax.naming.Context globalContext = null;
		MBeanServer mBeanServer = getMBeanServer();
		if (mBeanServer != null) {
			try {
				ObjectName name = new ObjectName("Catalina:type=Server");
				Server server = (Server) mBeanServer.getAttribute(name, "managedResource");
				//getGlobalNamingContext() was added to Server interface in Tomcat 7.0.11
				if (server instanceof StandardServer) {
					globalContext = ((StandardServer) server).getGlobalNamingContext();
				}
			} catch (Exception e) {
				logger.error("There was an error getting globalContext through JMX server:", e);
			}
		}
		
		return globalContext;
	}
	
	public void lookupResource(ApplicationResource resource, boolean contextBound, boolean global) {
	DataSourceInfo dataSourceInfo = null;
	if (contextBound) {
		try {
			javax.naming.Context ctx = !global ? new InitialContext() : getGlobalNamingContext();
			String jndiName = resolveJndiName(resource.getName(), global);
			Object o = ctx.lookup(jndiName);
	...
```

Tested on RHEL 7, Server JRE 1.8.0_40, Tomcat 8.0.21 and Probe 2.4.0-SNAPSHOT.

This is my first contribution, please let me know how it looks and how to attach the whole file.

**Comment by tssujatha** [comment]
fter OS upgrade from tomcat 8.0.36 to 8.0.43 (we are getting OS from SUSE linux (sles12-sp2-201702).the JNDI lookup is not working ,Actually My global resource look up for JNDI is happening properly with java:/resourcelink and when it comes to local reourcelink which is java:comp/env i am facing below issue which suppose to get the connetion ldap pool.

Provider.lookup jndi property java:comp/env/server/appname/LDIServiceLink could not be retrieved. The local resource link [LDIService] that refers to global resource [/server/appname/GlobalLDI] was expected to return an instance of [com.ldi.DirectoryService] but returned an instance of [java.util.HashMap]

See its returning hashmap but it suppose to be the class(type) object instance. This is exactly we are facing in intialcontext.lookup(jndipropname) One more added point here we are CDI injection also using weld-se.jar 2.3.3 jar. Please share if you have information on this.

**Comment by hazendaz** [comment]
Can you create a sample app with the issue?

Personally I think you might have a config issue.  Having worked closely with all tomcat versions since 6 with cdi and datasources up to 9.0.1 now without issue it's likely a config problem.  However with a sample use case that can show issue here is be more than happy to fix and release a new update.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tssujatha** [comment]
Below two ways it is working fine but its not a solution.
1.I have replaced catalina.jar with 8.0.36 in 8.0.43 it worked how it was working before in 8.0.36
    --The strange think is why its working with tomcat 8.0.36 catalina is there any specific changes made javax.naming or java.util. we are not getting the clue.
2. if we give the context entries in server.xml also it is working fine.
More importantly this tomcat 8.0.43 forcing the type parameter which we dint use it in our previous release of our applcication so we forced to use this type now(this also reason for the issue  i m facing) .
If you are not giving entry it throwing error its expecting type paramter so we gotta know this has been forced now.
When we add the context entry in server.xml we can do lookup proprely and the same we dont want to include the type context.xml as the type issue resolved in server level.

But giving the applixation related resource entries in server.xml is not advisable so we are not going to use the approach
here i have given the configuration we did in our application:

In server.xml

<GlobalNamingResources>
  <Resource auth="Container"
       factory="comi.adapter.NamingServiceFactoryAdapter"
       name="path/GlobalGUService"
       type="com.test.GroupAndUserService"
       directoryService="path/GlobalLDIService"/>

  </GlobalNamingResources>

In the context.xml:
<Context>
 <ResourceLink name="path/LDIService" global="path/GlobalLDIService" type="com..DirectoryService"/>
 <Realm className="com.adapter.TomcatDirectoryAdapter" directoryService="path/LDIService" allRolesMode="authOnly"/>
 <Valve className="com.adapter.TomcatAuthenticatorAdapter"/>
</Context>

In the application side:
We are injecting the properties through CDI and then the lookup is happening through inticalcontext.lookup(java:comp/env/path/LDIService"

PLease provide some hint how to rectify this.

**Comment by hazendaz** [comment]
You are describing tomcat direct behaviour changes best I can understand.  When you upgrade tomcat you mentioned only Catalina jar.  Did you update all tomcat jars?  Does your data source work fine just not visible in psi probe?  Can you provide am example rather than description?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tssujatha** [comment]
See actually i have migrated my code to tomcat 8.0.43 through suse linux sles12-sp2-201702.(they are the OS provider for our project) The one i have mentioned above replacing catalina is in this tomcat 8.0.43 only catalina.jar replaced with tomcat 8.0.36's catalina.jar all other jars are tomcat 8.0.43 jars.
I am not using psi-probe and all. 
We are using jndi and system properties to read the property files through CDI we are injecting those thats all our implementation.
I will try to give sample app i have to work on it.
Meanwhile could you please tel me what is the difference in this catalina compared to the existing one.
And any possible reason its returning hashmap instead of object instance. Please provide some hints.

**Comment by hazendaz** [comment]
I think you need to ask tomcat team.  Psi probe only manages tomcat.  It's not the provider.  Things do change from time to time and we try to support that under the hood but I generally think we would have known about this by now.  All versions of tomcat you mentioned this par are vulnerable.  Your best option is to be on latest of the supported ones and would need to confirm your code works there first.  Then if using psi probe something you expect doesn't work here the example app will help us track it down.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tssujatha** [comment]
Hello there,
Actually this issue resolved by adding the type="java.util.HashMap" to that resource link.
<ResourceLink global="path/GlobalLDIService" name="path/LDIServiceLink" type="java.util.HashMap" />

not sure this would be the correct soluntion and how it works.

**Comment by tssujatha** [comment]
Any suggestions on this?

**Comment by hazendaz** [comment]
@tssujatha Without a working example that I can physicaly test with there is little I can do.  This is also a very old issue that was fixed and merged per the issue tracking here.  So if you believe there is an existing problem on psi probe latest release (ie 3.0.0.RC2 not others are supported), then please file a new issue, provide a working sample to demonstrate the issue, and then I'll take a look.  I know you have indicated what you think the issue is so that too could mean you probably could providea  pull request to fix the issue but again a working example is the best way to get it resolve and a new issue.  Sorry I didn't notice you were commenting on an old fixed issue previously.
