### ISSUE TITLE
Error loading on JonAS 5.2 with Tomcat 6 embedded

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#421]
```
What steps will reproduce the problem?
1. Install probe.war on a JonAS 5.2 server
2. Go to /probe

What is the expected result?
Main page showing applications should show


What happens instead?
Error page showing the following stacktrace.

What version of Probe are you using?
2.3.3

What environment (browser version, Tomcat version, JVM version, server OS)?
Firefox 29.0.1, Tomcat 6, JDK 1.6.0_22, JonAS 5.2.1


Please provide any additional information below.
(Attach logs or stack traces as files instead of pasting the contents
here.)

java.lang.RuntimeException: No container found for your server: Apache 
Tomcat/6.0.32 at 
com.googlecode.psiprobe.controllers.apps.ListWebappsController.handleRequestInte
rnal(ListWebappsController.java:43) at 
org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractCon
troller.java:153) at 
org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(Simple
ControllerHandlerAdapter.java:48) at 
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.j
ava:875) at 
com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:54) at 
org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.ja
va:807) at 
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet
.java:571) at 
org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501
) at javax.servlet.http.HttpServlet.service(HttpServlet.java:617) at 
javax.servlet.http.HttpServlet.service(HttpServlet.java:717) at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:290) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.jav
a:129) at 
com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
 at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235) at 
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206) at 
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:2
33) at 
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:1
91) at 
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.jav
a:563) at 
org.ow2.jonas.web.tomcat6.CheckOpenResourcesValve.invoke(CheckOpenResourcesValve
.java:73) at 
org.ow2.jonas.web.tomcat6.tx.TransactionValve.invoke(TransactionValve.java:90) 
at 
org.ow2.jonas.web.tomcat6.ResetAuthenticationValve.invoke(ResetAuthenticationVal
ve.java:95) at 
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) 
at 
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) 
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:554) at 
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109
) at 
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298) at 
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859) at 
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Pr
otocol.java:588) at 
org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489) at 
java.lang.Thread.run(Thread.java:662) Caused by: java.lang.NullPointerException 
at 
com.googlecode.psiprobe.controllers.apps.ListWebappsController.handleRequestInte
rnal(ListWebappsController.java:41) ... 30 more


```

Original issue reported on code.google.com by `thebig...@gmail.com` on 26 Sep 2014 at 9:39

**Comment by hazendaz** [comment]
Given drop of tomcat 6 support on master, is this planned to be fixed on a separate branch or should it simply be closed?
