### ISSUE TITLE
Logback support broken psi-probe usage of slf4j 1.7.15+ with earlier slf4j-api versions

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#720]
As reported by @shentley on issue #719 and per logback news [here](http://logback.qos.ch/news.html)

February 11th, 2016, Release of version 1.1.4
Logback 1.1.4 requires SLF4J version 1.7.16 or later.

Added event replay support as introduced in SLF4J version 1.7.15. In most circumstances, logack-classic should run fine with earlier versions of slf4j-api, including all versions in the 1.6.x and 1.7.x series. However, with a version of slf4j-api.jar earlier than 1.7.15 in the classpath, attempting introspection of a Logger instance will result in a NoClassDefFoundError similar to that shown below.

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/event/LoggingEvent
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2451)
        at java.lang.Class.privateGetPublicMethods(Class.java:2571)
        at java.lang.Class.getMethods(Class.java:1429)
        at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1261)
        at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1122)
        at java.beans.Introspector.getBeanInfo(Introspector.java:414)
        at java.beans.Introspector.getBeanInfo(Introspector.java:161)
```

psi-probe is running slf4j 1.7.21 and logback 1.1.7.  User case had separate project using slf4j 1.7.5 and logback 1.0.13.

**Comment by hazendaz** [comment]
The reverse is also true.  If using the prior released snapshot that is still on older slf4j/logback, it crashes if project has newer modules.  The specific example I have is using newer logback such as 1.1.5 and slf4j 1.7.13.  It's a bit problematic that slf4j library is so unforgiving in this area and they had at least documented such a fact.

**Comment by hazendaz** [comment]
I have a partial fix that is still to be tested.  The idea is that we won't provide support for both as that is clearly documented as not possible.  Instead, we will catch the exception and indicate that users need to upgrade to consistent level.  By doing so, we will be breaking with convention on 3.0.0 and enforcing higher loggers.  I don't otherwise see any way around this.
