### ISSUE TITLE
Global Data sources not showing.

### ISSUE THREAD

**Issue by tonywestonuk** [psi-probe/psi-probe#947]
This error on Psiprobe v3.0.0 RC1 - However, it is not a new bug.. and, exists in 2.4 and previous prereleases of psiprobe v3

OS INFORMATION
jvm:  Java(TM) SE Runtime Environment  1.8.0_101-b13  Java HotSpot(TM) 64-Bit Server VM) 
os: Mac OS X (unknown) x86_64 10.12
processors: 8
current time: Sun Jan 01 20:08:14 GMT 2017
working dir: /

CONTAINER INFORMATION
container: Apache Tomcat/7.0.72

I get these logs:

.005 INFO {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /StackOverflow
20:02:00.005 INFO {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Reading CONTEXT /FriendlyStock_splits
20:02:00.005 ERROR {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Failed to lookup: 'jdbc/friendlystock_reloaded'
java.lang.NullPointerException: null
at psiprobe.beans.BoneCpDatasourceAccessor.canMap(BoneCpDatasourceAccessor.java:67)
at psiprobe.beans.BoneCpDatasourceAccessor.getInfo(BoneCpDatasourceAccessor.java:34)
at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:145)
at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:116)
at psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:212)
at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:196)
at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
20:02:00.005 ERROR {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Failed to lookup: 'jdbc/friendlystock_splits'
java.lang.NullPointerException: null
at psiprobe.beans.BoneCpDatasourceAccessor.canMap(BoneCpDatasourceAccessor.java:67)
at psiprobe.beans.BoneCpDatasourceAccessor.getInfo(BoneCpDatasourceAccessor.java:34)
at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:145)
at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:116)
at psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:212)
at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:196)
at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
20:02:00.005 ERROR {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Failed to lookup: 'jdbc/friendlystock'
java.lang.NullPointerException: null
at psiprobe.beans.BoneCpDatasourceAccessor.canMap(BoneCpDatasourceAccessor.java:67)
at psiprobe.beans.BoneCpDatasourceAccessor.getInfo(BoneCpDatasourceAccessor.java:34)
at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:145)
at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:116)
at psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:212)
at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:196)
at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
20:02:00.005 INFO {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Reading GLOBAL resources
20:02:00.005 INFO {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] reading resource: Catalina:type=Resource,resourcetype=Global,class=org.apache.catalina.UserDatabase,name="UserDatabase"
20:02:00.006 ERROR {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] There was an error getting globalContext through JMX server:
javax.management.InstanceNotFoundException: Catalina:type=Server
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
at psiprobe.beans.ResourceResolverBean.getGlobalNamingContext(ResourceResolverBean.java:299)
at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:140)
at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:76)
at psiprobe.beans.ContainerWrapperBean.getGlobalDataSources(ContainerWrapperBean.java:229)
at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:197)
at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
20:02:00.006 ERROR {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Failed to lookup: 'UserDatabase'
java.lang.NullPointerException: null
at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:142)
at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:76)
at psiprobe.beans.ContainerWrapperBean.getGlobalDataSources(ContainerWrapperBean.java:229)
at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:197)
at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
20:02:00.006 INFO {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] reading resource: Catalina:type=Resource,resourcetype=Global,class=javax.sql.DataSource,name="jdbc/gblfriendlystock"
20:02:00.006 ERROR {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] There was an error getting globalContext through JMX server:
javax.management.InstanceNotFoundException: Catalina:type=Server
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
at psiprobe.beans.ResourceResolverBean.getGlobalNamingContext(ResourceResolverBean.java:299)
at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:140)
at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:76)
at psiprobe.beans.ContainerWrapperBean.getGlobalDataSources(ContainerWrapperBean.java:229)
at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:197)
at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
20:02:00.006 ERROR {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Failed to lookup: 'jdbc/gblfriendlystock'
java.lang.NullPointerException: null
at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:142)
at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:76)
at psiprobe.beans.ContainerWrapperBean.getGlobalDataSources(ContainerWrapperBean.java:229)
at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:197)
at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
20:02:00.006 INFO {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] reading resource: Catalina:type=Resource,resourcetype=Global,class=javax.sql.DataSource,name="jdbc/gblfriendlystock_splits"
20:02:00.006 ERROR {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] There was an error getting globalContext through JMX server:
javax.management.InstanceNotFoundException: Catalina:type=Server
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
at psiprobe.beans.ResourceResolverBean.getGlobalNamingContext(ResourceResolverBean.java:299)
at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:140)
at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:76)
at psiprobe.beans.ContainerWrapperBean.getGlobalDataSources(ContainerWrapperBean.java:229)
at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:197)
at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
20:02:00.006 ERROR {Probe_Quartz-2} [psiprobe.beans.ResourceResolverBean] Failed to lookup: 'jdbc/gblfriendlystock_splits'
java.lang.NullPointerException: null
at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:142)
at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:76)
at psiprobe.beans.ContainerWrapperBean.getGlobalDataSources(ContainerWrapperBean.java:229)
at psiprobe.beans.ContainerWrapperBean.getDataSources(ContainerWrapperBean.java:197)
at psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean.collect(DatasourceStatsCollectorBean.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

The config part in server.xml

  <GlobalNamingResources>
    
    <Resource name="UserDatabase" auth="Container"
              type="org.apache.catalina.UserDatabase"
              description="User database that can be updated and saved"
              factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
              pathname="conf/tomcat-users.xml" />

<Resource auth="Container" driverClassName="org.postgresql.Driver" maxActive="10" maxIdle="5" maxWait="20000" name="jdbc/gblfriendlystock" password="" type="javax.sql.DataSource" url="jdbc:postgresql://127.0.0.1:5432/friendlystock?prepareThreshold=3" username=""/>

<Resource auth="Container" driverClassName="org.postgresql.Driver" maxActive="15" maxIdle="5" maxWait="20000" name="jdbc/gblfriendlystock_splits" password="" type="javax.sql.DataSource" url="jdbc:postgresql://127.0.0.1:5432/friendlystock_splits?prepareThreshold=3" username=""/>

</GlobalNamingResources>

**Comment by hazendaz** [comment]
Can you try building off master to see if that helps?  If so, I'll release RC2.  It has a number of fixes over RC1 which might help with this issue.

**Comment by tonywestonuk** [comment]
No, Sorry..... Didn't solve it.  Get the same exceptions (posted again below as the linenumbers probably changed)

20:20:16.290 ERROR {http-nio-83-exec-773} [psiprobe.beans.ResourceResolverBean] Failed to lookup: 'jdbc/gblfriendlystock_splits'
java.lang.NullPointerException: null
at psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:143)
at psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:77)
at psiprobe.beans.ContainerWrapperBean.getGlobalDataSources(ContainerWrapperBean.java:239)
at psiprobe.controllers.datasources.ListAllJdbcResourcesController.handleRequestInternal(ListAllJdbcResourcesController.java:49)
at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)
at psiprobe.controllers.datasources.ListAllJdbcResourcesController.handleRequest(ListAllJdbcResourcesController.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
at psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:86)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:121)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
at psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:40)
at psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:58)
at psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:58)
at psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:58)
at psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:58)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1083)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:640)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)

**Comment by hazendaz** [comment]
Definitity a different spot and much sooner...

```
        Object obj = ctx.lookup(jndiName);
```
context is null there.  RC1 must have worked at that point which was then sent to the accessor which failed upon reference to it.

Is there anything special about your setup that I might be able to use to replicate issue?  Also, one thing you might try if you happen to know where it last worked is to perform some git checkouts pulling in a few PRs at a time until it breaks.  That would definitely help isolate the issue.  I've yet to see this issue.  I'm using mariadb test database for testing purposes and it's been working fine.  Possibly you can assist in telling me what else to setup that might cause this to occur.

**Comment by tonywestonuk** [comment]
My config is:

  <GlobalNamingResources>
    
    <Resource name="UserDatabase" auth="Container"
              type="org.apache.catalina.UserDatabase"
              description="User database that can be updated and saved"
              factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
              pathname="conf/tomcat-users.xml" />

<Resource auth="Container" driverClassName="org.postgresql.Driver" maxActive="10" maxIdle="5" maxWait="20000" name="jdbc/gblfriendlystock" password="" type="javax.sql.DataSource" url="jdbc:postgresql://127.0.0.1:5432/friendlystock?prepareThreshold=3" username=""/>

<Resource auth="Container" driverClassName="org.postgresql.Driver" maxActive="15" maxIdle="5" maxWait="20000" name="jdbc/gblfriendlystock_splits" password="" type="javax.sql.DataSource" url="jdbc:postgresql://127.0.0.1:5432/friendlystock_splits?prepareThreshold=3" username=""/>

</GlobalNamingResources>


And then I get to these resources by having a context.xml in my webapp: However, I have just checked, and I notice 3 resource links in my context.xml, rather than the two that are in my web.xml - this is a bug in my code (i'll fix!)..... maybe this is causing psyprobe not to list any of them?

<?xml version="1.0" encoding="UTF-8"?>
<Context aliases="/gifts=/usr/local/tomcat/static/gifts">
 <ResourceLink global="jdbc/gblfriendlystock" name="jdbc/friendlystock" type="javax.sql.DataSource"/>
 <ResourceLink global="jdbc/gblfriendlystock_reloaded" name="jdbc/friendlystock_reloaded" type="javax.sql.DataSource"/>
 <ResourceLink global="jdbc/gblfriendlystock_splits" name="jdbc/friendlystock_splits" type="javax.sql.DataSource"/>

</Context>

**Comment by hazendaz** [comment]
Ok - if that fixes it let me know and I'll look at setting up a misconfiguration like that and try to trap that so it doesn't crash ;)

**Comment by hazendaz** [comment]
By chance did you have this log message -> '"There was an error getting globalContext through JMX server:'

**Comment by tonywestonuk** [comment]
Yes!!

20:47:33.467 ERROR {http-nio-83-exec-21} [psiprobe.beans.ResourceResolverBean] There was an error getting globalContext through JMX server:
javax.management.InstanceNotFoundException: Catalina:type=Server


I can zip up my tomcat directory (without my apps), and send it to you?

**Comment by hazendaz** [comment]
No need.  Since that error occurred, it should not have tried to continue processing with it.  So let me make a quick patch to at least skip by the error.  Then you can test again and see if that at least allows you to work even if misconfigured.  Give me about 15 minutes or so to get something in here.

**Comment by hazendaz** [comment]
ok - with that misconfiguration, please try again off master and see if that works any better.  My tests were at application level so I'll add in global shortly so I've got that covered.  Also, if you don't mind work off master for a while and let me know if you run into any issues.  If that seems all good, I'm going to release RC2 shortly thereafter and ultimately 3.0.0 officially in next week or so.  My future plans then are to get on a monthly release cycle for this project for the future.  For now I'm just trying to shake out any errors so this is a smooth release :)

**Comment by tonywestonuk** [comment]
ok, if you want - here is my tomcat dir, with probe installed.

https://www.friendlystock.co.uk/FriendlyStock_splits/gifts/probe_datasource_error.tar.gz

Unzip, run, and connect to probe on localhost:1083/probe  - username/password is qaz

**Comment by hazendaz** [comment]
got it!  thanks.

**Comment by hazendaz** [comment]
I see the version issue too.  I had just moved things around so probably missed the piece maven does.  Looking at fixing that now.  Also getting setup configuration you have and will be testing that shortly too.  Thanks.

**Comment by hazendaz** [comment]
@tonywestonuk Sorry got side tracked with the 'version' issue.  Back on global now and have repeated the last error you noted.  Good news is that I'm probably close to getting this solved ;)

**Comment by hazendaz** [comment]
@tonywestonuk 

I'm not 100% sure this is a psi probe issue.  I found the issue and got it working but to make it exposible it would require new changes to psi probe.  Your engine name is 'Catalina_facebook'.  Internally, that is what is exposed via JMX.  Psi probe has this line of code.

```
ObjectName name = new ObjectName("Catalina:type=Server");
```

If I change it to the engine you are using...

```
ObjectName name = new ObjectName("Catalina_facebook:type=Server");
```

It then works.  Obviously this is a hard coded value so that is bad on psi probe side.  However, need a bit more input from you as to why one might want to do this.  We certainly can make this configurable but want to make sure that is the right approach here and not simply a misconfiguration.  If you could elaberate a bit on why you are doing this that will help out.

Thanks...

Jeremy

**Comment by hazendaz** [comment]
I have a fix that will satisfy a single change in this.  It will read through all domains which will make this work for your use case.  I've tested it against my copy and it worked without issue so now testing against your instance.  If it works, I'll push it up shortly.  It might not be a final solution but at least should work for you.

**Comment by tonywestonuk** [comment]
Ahh,  Thats why it didn't work!  Thank you for finding it.

For info, my tomcat instance runs 3 facebook games, and 5 websites.  The two are separated into two service engines, catalina_facebook and catalina_websites,  which then can be configured separately.   I guess I should put them onto separate tomcat instances, though with a limited amount of server resource (memory), would rather run everything in a single JVM.

I did remove the catalina_websites out of the config before sending it to you.

But, thanks again on finding this issue that has haunted me for so long!

**Comment by hazendaz** [comment]
Fix is on master so you should be good now.  Let me know how multiple engines work as I only tested with the one.  I suspect it should work fine in that area but might be other areas to look at in such a configuration.
