### ISSUE TITLE
There was an error when click on the connectors tab, and good news...

### ISSUE THREAD

**Issue by tachtler** [psi-probe/psi-probe#979]
Hi Jeremy,

**a)** first the good news, click on the language flag are working again, thank you for that!

**b)** second good news, the TAB "Deployment", with "upload application basic" shows after deployment the successful block again, you solved that to, thank you for that too. (no blank screen will be shown anymore)

**c)** sorry for that, but when I click on the TAB "connectors" the following error still occurs:

**There was an error**

> Application encountered an unexpected error. Please check the Tomcat logs. We will greatly appreciate it if you share the information with us. Sharing this information through our issue tracker or our discussion board will help us find and correct this problem as soon as possible!

```
Jan 10, 2017 6:41:09 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [probe] in context with path [/probe] threw exception [Request processing failed; nested exception is javax.management.RuntimeOperationsException: Exception invoking method remoteAddr] with root cause
java.lang.NullPointerException
        at org.apache.coyote.http11.Http11AprProcessor.actionInternal(Http11AprProcessor.java:268)
        at org.apache.coyote.http11.AbstractHttp11Processor.action(AbstractHttp11Processor.java:910)
        at org.apache.coyote.Request.action(Request.java:345)
        at org.apache.coyote.RequestInfo.getRemoteAddr(RequestInfo.java:97)
        at sun.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.util.modeler.BaseModelMBean.getAttribute(BaseModelMBean.java:190)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
        at psiprobe.tools.JmxTools.getAttribute(JmxTools.java:51)
        at psiprobe.tools.JmxTools.getStringAttr(JmxTools.java:154)
        at psiprobe.beans.ContainerListenerBean.getConnectors(ContainerListenerBean.java:297)
        at psiprobe.controllers.connectors.ListConnectorsController.handleRequestInternal(ListConnectorsController.java:123)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)
        at psiprobe.controllers.connectors.ListConnectorsController.handleRequest(ListConnectorsController.java:115)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:121)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:40)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
        at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:188)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2517)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2506)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```
Actual system informations, where the error still occurs:
```
OS information
JVM:  OpenJDK Runtime Environment  1.8.0_111-b15  OpenJDK 64-Bit Server VM)
OS: Linux (CentOS 7.3) amd64 3.10.0-514.2.2.el7.x86_64
Processors: 2
Current time: Tue Jan 10 06:52:34 CET 2017
Working dir: /usr/share/tomcat
Container information
Container: Apache Tomcat/7.0.69
catalina.base: /usr/share/tomcat
catalina.home: /usr/share/tomcat
Application base: /usr/share/tomcat/webapps
Configuration base: /usr/share/tomcat/conf/localhost
```

Thank you!
Klaus

**Comment by hazendaz** [comment]
Cool.  Thanks this gave me more to go on than before.  I have restored a try catch around

```
psiprobe.beans.ContainerListenerBean.getConnectors(ContainerListenerBean.java:297)
```

Please rebuild off master and let me know if this does the trick.  If so, if you would so kindly check to see if there are any other issues.  Provided we got everything I'll push RC2 which will become final in a week or so after that soaks in.  Thanks so much for helping out with this!

**Comment by tachtler** [comment]
Hi Jeremy,

# yes it works, great job!

Found a view graphical issues, I will open a new bug report, to describe what I found, o.k.?

## Thank you!
Klaus.

**Comment by hazendaz** [comment]
Sounds good.  Please do open as many issues as you find.  Thanks again.

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Jan 11, 2017 at 6:40 AM -0500, "Klaus Tachtler" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jeremy,

yes it works, great job!

Found a view graphical issues, I will open a new bug report, to describe what I found, o.k.?

Thank you!

Klaus.
